### ISSUE TITLE
Deploy an updated network

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#10100]
For the deployment of the test-snapps testnet, see this README.

https://github.com/MinaProtocol/mina/pull/10119/files#diff-624550978174a16324fe1ab51d9125c16da0650c6df4d37ed22d8e75a6d29d90R1

**Comment by QuiteStochastic** [comment]
As of rn, there's a test-snapps testnet running in us-central-1, running an image off the tip of `feature/snapps-protocol`.  However, `feature/snapps-protocol` as of right now does not have the latest 1.3alpha3/1.3beta1 changes, and still has within it the staged ledger bug from 1.3alpha2, and because of this bug i expect that after a few days of runtime at most, the nodes on test-snapps will start to de-sync and get stuck, just as we saw happen to nodes running 1.3alpha2 on mainnet.

Work remaining: firstly we are blocked by the branch `feature/snapps-protocol` needing to be rebased on the latest tip of develop containing the changes from 1.3beta1.  Once that's done, we plan to make a test-snapps docker image that can be distributed to interested community members.

**Comment by QuiteStochastic** [comment]
next phase of this: create a package and docker image not only running the latest snapps code, but also hardcoded with the test-snapps testnet genesis ledger.  to this end, the genesis ledger of devnet needs to be incorporated into the test-snapps genesis ledger.
