### ISSUE TITLE
update the constant `transaction_expiry_hr`

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#10202]
Set it to 2 hours for the qanet but this might need to be updated before testnet

**Comment by deepthiskumar** [comment]
Remove transaction_expiry_hr

**Comment by ghost-not-in-the-shell** [comment]
If we just want to remove the config `transaction_expiry_hr` and make `expiry_ns` of `network_pool` non-configurable. Then this would be a small change. Otherwise, if we also want to remove `expiry_ns`, then this would be a little complicated. We need to also remove the logic for expiry related things in transaction pool and also remove all the related tests.

**Comment by deepthiskumar** [comment]
Removed the constant- https://github.com/MinaProtocol/mina/pull/12231
