### ISSUE TITLE
Investigation: snark work inclusion rate

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#10430]
Investigate the low snark work inclusion rate on the network. Note that this is not the first investigation, this just tracks the most recent one.

**Comment by jrwashburn** [comment]
There seems to be a pattern where snark work is purchased sporadically in large batches. When network traffic is minimal, block producers will buy snarks up to 128, but then do not buy snarks again until there is something that seems to trigger a new purchase. This can be seen on a daily basis under normal conditions, but is not obviously explained by understood snark purchasing strategies.

<img width="1329" alt="Screen Shot 2022-03-07 at 12 40 19 PM" src="https://user-images.githubusercontent.com/891888/157097115-0def7e9a-79cc-496b-92a7-f67ddfd0d735.png">

This is a distribution of snarks purchased per block since the beginning of mainnet:
![image](https://user-images.githubusercontent.com/891888/157097341-093e3873-452c-4eba-8c11-d4b94d802bf0.png)

It is suspected that this batching behavior (or failure of BP to purchase snarks) may contribute to lower transaction fill rates in blocks. This is just a suspicion based on transactions per block and snark worker activity, but is not demonstrable yet.

**Comment by yourbuddyconner** [comment]
This issue has been mentioned on **MinaResearch**. There might be relevant details there:

https://forums.minaprotocol.com/t/discussions-on-the-snarketplace-design/5394/12

**Comment by nholland94** [comment]
@jrwashburn Thanks for posting your analysis.

I'm closing this issue for now as part of a new issue tracking process we are trying out internally. This *does not* mean that the investigation is over, rather that we wish to capture various investigation efforts separately. Rest assured, we will be continuing to look into this.

We have been unable to collect useful information from mainnet in order to debug this issue. As such, we are focusing our efforts on the devnet environment where we are more easily able to iterate over debug builds on block producing nodes. The effort for this work is captured in the followup investigation issue ##10681.

**Comment by nholland94** [comment]
@jrwashburn Thanks for posting your analysis.

I'm closing this issue for now as part of a new issue tracking process we are trying out internally. This *does not* mean that the investigation is over, rather that we wish to capture various investigation efforts separately. Rest assured, we will be continuing to look into this.

We have been unable to collect useful information from mainnet in order to debug this issue. As such, we are focusing our efforts on the devnet environment where we are more easily able to iterate over debug builds on block producing nodes. The effort for this work is captured in the followup investigation issue ##10681.
