### ISSUE TITLE
Expose Kimchi APIs - Research

### ISSUE THREAD

**Issue by carterbrett** [MinaProtocol/mina#10604]
### Objective
To expose Kimchi APIs and create the necessary documentation and examples for it to be used by others.

**Comment by querolita** [comment]
I had a chat with @mimoo, who gave me some really useful hints about the things we could address in order to expose Kimchi API. Let me summarize it here:

- First and foremost, we would like users to be able to write circuits in Rust. @imeckler has some preliminary [piece of code for this](https://github.com/imeckler/bba/blob/update-for-kimchi/src/bba_init_proof.rs#L31) that we may want to have a PR for. 
- A way to use recursion, which is something Matthias will be working on
- Improve our documentation and metrics
  - We should write a good README with code examples about how to use the different modules one would need
  - A book would be great in the future, but it should not be a priority yet.
- Some usability enhancements such as:
  - Create a type for `Witness` instead of just arrays of vectors. There is some work in progress for this in the [PR 343](https://github.com/o1-labs/proof-systems/pull/343)
  - Serialize the proof into bytes. There is [issue 434](https://github.com/o1-labs/proof-systems/issues/434) for this. 
    - But [issue 231](https://github.com/o1-labs/proof-systems/issues/231) is blocking it. 
    - It looks like it can make more sense to address [issue 432](https://github.com/o1-labs/proof-systems/issues/432), for which a contributor is collaborating. 
    - xiangxecrypto has recently created the [PR 467](https://github.com/o1-labs/proof-systems/pull/467) addressing the issue, it is being reviewed.
- The current codebase is full of public functions that can be called from outside. We may want to study what functionalities are really meant to be public and which should not.
- Push our libraries to [crates.io](crates.io) 
  - This would imply to have a release cycle
  - A register of the versions of the library
  - A change log between versions
  - Some crates need a tool to be published altogether. @mimoo created [this issue](https://github.com/o1-labs/ocaml-gen/issues/7) to decide about `ocaml-gen`
    - We should aim to include this in CI (perhaps we could use [CLAP](https://docs.rs/clap/latest/clap/) to make it easier)
