### ISSUE TITLE
Ethereum Primitives - Phase 2

### ISSUE THREAD

**Issue by carterbrett** [MinaProtocol/mina#10603]
### Objective
To add support to kimchi for signing arbitrary data with ECDSA over Ethereum's `sekp256k1` curve. 

**Related to #10602**

**Comment by joseandro** [comment]
@querolita does the last remaining issue left in this epic correctly conveys what's left to finish it?

**Comment by querolita** [comment]
@joseandro Not sure what last remaining issue you're referring to, but there is still a long way ahead until this epic can be considered finished. Perhaps linking epics with each other could be a good idea in this case, because this epic itself depends on the FFMul epic and Keccak as well. A summary of what's left follows:

- Finish and test FFmul
- Refactor RangeCheck for chaining reasons
- Merge Rotation
- Write the Keccak gadget using Rot and Xor
- Write the ECadd gadget using FFadd, FFmul and RC
- Write the ECdouble gadget using FFadd, FFmul and RC
- Write the curve operations gadget using ECadd and ECdouble
- Write the ECDSA gadget

**Comment by joseandro** [comment]
@jspada I believe we can close this epic, no?

**Comment by joseandro** [comment]
I am closing this epic since we are switching to gadgets https://app.zenhub.com/workspaces/core-crypto-621fcb82b7d49700156fd060/issues/gh/minaprotocol/mina/12555 and https://app.zenhub.com/workspaces/core-crypto-621fcb82b7d49700156fd060/issues/gh/minaprotocol/mina/12556
