### ISSUE TITLE
Include proofs in interaction transactions with zkapps

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#10616]

**Comment by mitschabaude** [comment]
This included two tasks:
* [x] add authorization (proof /signature) to snarkyjs' tx interface
* [x] serialize proofs produced by our Pickles provers in the format expected in a transaction

For the second task, it turned out that we had to fix the max number of merged proofs per zkapp (`max_branching`) to 2. This is bad for the average developer, who won't need to merge any proofs, and thus could have much faster compile & prove times with `max_branching=0`. Will track that in a separate issue.
