### ISSUE TITLE
Create a new DB in the production postgres instance with the Berkeley schema

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#10911]

**Comment by matheus-o1labs** [comment]
Hi @lk86  can you share the last version for the Berkeley schema?

adding @joseandro  @stevenplatt  for visibility on the matter.

**Comment by stevenplatt** [comment]
To recreate an instance of the current BerkeleyDB, it is recommended to take a dump from the currently running testnet, and import this data into the newly created DB on the CloudSQL Postgres instance. 

There are two SQL instance running in Berkeley currently `archive-3-postgresql` and `archive-1-postgresql`. 
All the moment, all Berkeley-related infra deployment is located in the `coda-infra-central1` kubernetes cluster, within the `berkeley` namespace. Viewing the workloads within that cluster and namespace will also show the archive nodes, and other nodes in the network is you need to compare to check certain status items. 

Creating a dump from berkeley would use a command similar to: 
`pg_dump --no-owner --create postgres://postgres:foobar@archive-3-postgresql:5432/archive_balances_migrated > $FILENAME`. 
You can view the kubernetes cron yaml running on mainnet to perform this dump [here](https://console.cloud.google.com/kubernetes/cronjob/us-east1/coda-infra-east/mainnet/mainnet-dump-archive-cronjob/yaml/view?authuser=1&project=o1labs-192920). (line 96)

**Comment by stevenplatt** [comment]
An additional note relating to this, is that once the new database version is online; it would also be necessary to eventually validate the existing cron jobs that run on the mainnet database, to confirm they still function and can be run against the new database instance and schema. This may be most important for the `replayer` job. Once the new database is imported and online, the next version of the Berkeley Testnet (incentivized) is expected to point to that new instance of Berkeley DB instead of using a locally installed instance of postgres.
