### ISSUE TITLE
Create a CI dashboard

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#10922]
Required metrics this dashboard should display:
- [ ]  Common CI failure types.
- [ ]  How often they happen.
- [ ]  Average time a build waits to be picked up by Buildkite nodes.
- [ ]  Average build time
- [ ]  Top Y flakiest integration tests in the last X months

These statistics will allow us to measure how our changes are improving our infrastrucutre. Other metrics are welcome.

**Comment by bryanhonof** [comment]
Would [BuildKite's Test Analytics ](https://buildkite.com/test-analytics) suffice?

**Comment by michal0mina** [comment]
tagging myself @michal0mina and @kaozenn to remember about those stats

**Comment by robinbb** [comment]
@michal0mina This issue would not be required if the CI were always green, of course. What a dashboard cannot easily say is whether a test is red correctly, or due to flakiness. Is there an issue that is like "make all CI tests go green" or "handle all flaky tests in CI" that we can use to replace this issue?
