### ISSUE TITLE
Upgrade to latest OCaml version

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#10940]
EDIT by @Firobe:  Upgrade the compiler and needed packages for OCaml `4.14.0` if possible.

**Comment by Firobe** [comment]
Initial conflicts during upgrade to `4.14`, as shown by opam.  

```
  ⊘ remove    rpc_parallel            v0.13.0*           [conflicts with ocaml]
  ⊘ remove    graphql_ppx             0.0.4*             [conflicts with ocaml]
  ⊘ remove    ppx_deriving_yojson     3.5.3*             [conflicts with ocaml]
  ⊘ remove    caqti-async             1.3.0              [conflicts with ocaml]
  ⊘ remove    graphql-async           0.13.0             [conflicts with ocaml]
  ⊘ remove    graphql_ppx_base        0.0.4*             [conflicts with ocaml]
  ⊘ remove    cohttp-async            2.5.2-1            [conflicts with ocaml]
  ⊘ remove    ppxfind                 1.4                [conflicts with ocaml]
  ⊘ remove    ppx_tools_versioned     5.4.0              [conflicts with ocaml]
  ⊘ remove    conduit-async           4.0.0              [conflicts with ocaml]
  ⊘ remove    async_ssl               v0.13.0            [conflicts with ocaml]
  ⊘ remove    async                   v0.13.0            [conflicts with ocaml]
  ⊘ remove    async_unix              v0.13.1            [conflicts with ocaml]
  ⊘ remove    async_rpc_kernel        v0.13.0            [conflicts with ocaml]
  ⊘ remove    async_kernel            v0.13.0*           [conflicts with ocaml]
```

73 packages are otherwise upgraded in the process

There's no guarantees the code base will correctly build after the conflicts are fixed, but it's the first obstacle. Most of the conflicts are seemingly simply because these packages are pinned.

**Comment by Firobe** [comment]
The reason `ppx_deriving_yojson` is pinned is because in the past a fix from a newer version was manually backported. It now can safely be upgraded to that newer version and we can remove the pin and submodule altogether.

This makes `ppxfind` removal OK, since it's only use was in the legacy version of `ppx_deriving_yojson`.

Actions:
- remove pin on `ppx_deriving_yojson`
- remove `ppxfind`

New list of conflitcts:
```
  ⊘ remove    rpc_parallel            v0.13.0*           [conflicts with ocaml]
  ⊘ remove    graphql_ppx             0.0.4*             [conflicts with ocaml]
  ⊘ remove    caqti-async             1.3.0              [conflicts with ocaml]
  ⊘ remove    graphql-async           0.13.0             [conflicts with ocaml]
  ⊘ remove    graphql_ppx_base        0.0.4*             [conflicts with ocaml]
  ⊘ remove    cohttp-async            2.5.2-1            [conflicts with ocaml]
  ⊘ remove    ppx_tools_versioned     5.4.0              [conflicts with ocaml]
  ⊘ remove    conduit-async           4.0.0              [conflicts with ocaml]
  ⊘ remove    async_ssl               v0.13.0            [conflicts with ocaml]
  ⊘ remove    async                   v0.13.0            [conflicts with ocaml]
  ⊘ remove    async_unix              v0.13.1            [conflicts with ocaml]
  ⊘ remove    async_rpc_kernel        v0.13.0            [conflicts with ocaml]
  ⊘ remove    async_kernel            v0.13.0*           [conflicts with ocaml]
```

**Comment by Firobe** [comment]
Most `async` conflicts are due to the fact that `async_kernel` is tied to the `v0.13` version of the Jane Street ecosystem (same for `rpc-parallel`. We need to either:
- rebase Mina changes on `async_kernel` and `rpc_parallel` on a newer version of both of these packages
- relax the `"core_kernel" {< "v0.14"}` on both of the packages, and fix any problem that might happen

The first solution would obviously be more preferable, but I don't know yet how much work that would represent.

**Comment by Firobe** [comment]
The `graphql_ppx` conflict is because it needs `ppx_versioned_tools`, which needs on old version of `ocaml-migrate-parsetree`, incompatible with newer OCaml versions.

Ideally, the usage of `ppx_versioned_tools` should be replaced by `ppxlib`. In the long term, hopefully `graphql_ppx` can be replaced altogether.

In the meantime, we can try to relax constraints where possible.

**Comment by Firobe** [comment]
> Most `async` conflicts are due to the fact that `async_kernel` is tied to the `v0.13` version of the Jane Street ecosystem (same for `rpc-parallel`. We need to either:
> 
>     * rebase Mina changes on `async_kernel` and `rpc_parallel` on a newer version of both of these packages
> 
>     * relax the `"core_kernel" {< "v0.14"}` on both of the packages, and fix any problem that might happen
> 
> 
> The first solution would obviously be more preferable, but I don't know yet how much work that would represent.

Experimenting with the second solution, the following actions resolve the conflicts:
- relax constraints on all async and Jane Street packages from `< 0.14` to `< 0.15` in `rpc_parallel` and `async_kernel`
- artificially change the version of `async_kernel` from `0.13` to `0.14`

Every package correctly upgrades and rebuilds correctly, except:
- `extlib` because of the old pin. It seems the pin is not needed anymore, because its only change is now incorporated in the last upstream version. Removing the pin and installing the upstream version works.
- `rpc_parallel`, because of an interface change. I'm investigating.

**Comment by Firobe** [comment]
>     * `rpc_parallel`, because of an interface change. I'm investigating.
This can be easily resolved by minor changes in `rpc_parallel`, mostly due to the interface change of `failwiths` in the new `core` version. It would be even better (and probably feasible, for rpc_parallel), to rebase on the latest version of `rpc_parallel`, which contains the same changes.

**Comment by Firobe** [comment]
The road is now free to upgrade OCaml itself!

**Comment by robinbb** [comment]
@Firobe Is there an issue for that task? Is it in this epic? What remains in order to close this epic?

**Comment by Firobe** [comment]
@robinbb There is one last PR to be made (this week) to actually bump OCaml (and fix related breakages). It'll be associated directly to this epic, instead of a sub-issue.

**Comment by robinbb** [comment]
Congratulations on the closing of this issue, @Firobe ! Well done!
