### ISSUE TITLE
Extract over-the-wire types into a separate library

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#11101]
Currently, the types that we send over the network and between processes are scattered across the codebase, bundled together with code that isn't necessarily useful to consumers of the type. This causes a lot of inter-dependence between libraries, and a lot of code to be linked into smaller / single-purpose executables -- in particular, the Mina signer and SnarkyJS.

We also have poor visibility into the end-to-end structure of the messages sent over the protocol, where discovering the actual data requires a lot of manual searching.

To combat these issues, we can factor out the 'over-the-wire' types into a dedicated library (e.g. `Mina_wire_types`) that contains these types only. To keep this library as minimal as possible, it would be best to avoid adding derivers to these types too, since they can be added via aliases later. For example,
`mina_wire_types.ml`:
```ocaml
module Transaction = struct
  type transaction = ..
end
```
`transaction.ml`:
```ocaml
type t = Mina_wire_types.Transaction.t = .. [@@deriving foo, bar]
```

------

We also have some private/opaque types scattered about the protocol, most notably those from `Currency`. For these, it might make sense to have some kind of 'revealing' functor, e.g.
`mina_wire_types.ml`:
```ocaml
module type Signature = sig
  module Mk : functor (A : sig type t end) -> sig module type S end
end

module Amount = struct
  type t = Unsigned.UInt64.t
end

module Mk_amount
    (Signature : Signature)
    (F : functor (A : sig type t = Unsigned.UInt64.t end) -> Signature.Mk(A).S)
  : Signature.Mk(Amount).S =
  F(Amount)
```
`mina_wire_types.mli`:
```ocaml
module type Signature = sig
  module Mk : functor (A : sig type t end) -> sig module type S end
end

module Amount : sig
  type t = private Unsigned.UInt64.t
end

module Mk_amount
    (Signature : Signature)
    (F : functor (A : sig type t = Unsigned.UInt64.t end) -> Signature.Mk(A).S)
  : Signature.Mk(Amount).S
```
`amount.ml`:
```ocaml
module Signature (A : sig type t end) = struct
  module type S = Intf.S with type t = t
end
include Mina_wire_types.Mk_amount
    (Signature)
    (functor (A : sig type t = Unsigned.UInt64.t end) -> struct
      type t = A.t [@@deriving foo, bar]
    end)
```

-----

- [x] Proof of concept for `Currency.Amount.t`: https://github.com/MinaProtocol/mina/pull/11256 & https://github.com/MinaProtocol/mina/pull/11326
- [x] Apply design to all types up to `Mina_transaction`

**Comment by robinbb** [comment]
@Firobe You are the likely assignee of this work, and this work deemed to be of higher priority than the issues that you are currently working on, FYI. (This is because it is a blocker for other work which must start in ~2 weeks.)

**Comment by Firobe** [comment]
@mrmr1993 I have a few questions:
- if I want to do this, how do I discover what types should end up here? I assume they are a subset of all versioned types
- I understand your examples for private/abstract types but I fail to see the point of having such types in the library in the first place. In your example, no value of type `Mina_wire_types.Amount.t` can ever be constructed, so values obtained through `Mk_amount` won't be compatible with functions across the codebase expecting to consume/deconstruct a `Mina_wire_types.Amount.t`. Maybe it would be clearer if I had an idea of how you expect such private/abstract types would be used after being separated in their own library.
- Is the idea of the "revealing" functors just to check that the concrete type in `amount.ml` matches the one in `mina_wire_types.ml` (but then, why even have concrete types `mina_wire_types.ml` with concrete types, except for documentation?).

Also a small remark, in your examples as is, functions cannot be derived here
```ocaml
(functor (A : sig type t = Unsigned.UInt64.t end) -> struct
      type t = A.t [@@deriving foo, bar]
    end)
```
since `ppx_deriving` is looking for `A.pp` (for `show`, for example) and isn't smart enough to follow the type equation to `Unsigned.Uint64.pp`. But this can probably be worked around via other means, depending on the kind of `t`.

**Comment by Firobe** [comment]
Proof of concept for `Currency.Amount` is validated and now merged: https://github.com/MinaProtocol/mina/pull/11256

Now working on applying the same design to the rest of the types

**Comment by Firobe** [comment]
WIP list documenting all types needed:

%: already visited
?: children not visited yet
$: repeat prefix above

## Compatible

Network_pool.Transaction_pool.Diff_versioned.V1.t
- Mina_base.User_command.t
  - $.$.Poly.Stable.V1.t
  - $.Signed_command.Stable.V1.t
    - $.$.Poly.Stable.V1.t
    - $.Signed_command_payload.Stable.V1.t
      - $.$.Poly.Stable.V1.t
      - $.$.Common.Stable.V1.t
        - $.$.$.Poly.Stable.V1.t
        - Currency.Fee.Stable.V1.t
        - Public_key.Compressed.Stable.V1.t
          - Non_zero_curve_point.Compressed.Stable.V1.t ?
        - $.Token_id.Stable.V1.t
          - Mina_numbers.Nat.Make64.Stable.V1.t ?
        - Mina_numbers.Account_nonce.Stable.V1.t ?
        - Mina_numbers.Global_slot.Stable.V1.t ?
        - $.Signed_command_memo.Stable.V1.t
      - $.$.Body.Stable.V1.t
        - $.Payment_payload.t
          - Poly.Stable.V1.t
          - Currency.Amount.Stable.V1.t
          - %
        - $.Stake_delegation.t
          - %
        - $.New_token_payload.t
          - %
        - $.New_account_payload.t
          - %
        - $.Minting_payload.t
          - %
    - Public_key.Stable.V1.t
      - Non_zero_curve_point.Stable.V1.t ?
    - $.Signature.Stable.V1.t ?
  - $.Snapp_command.Stable.V1.t ?

Network_pool.Snark_pool.Diff_versioned.Stable.V1.t ?

Mina_block.External_transition.Raw.Stable.V2.t ?

## Develop

?

**Comment by Firobe** [comment]
As discussed with Matthew, I'm restricting the scope of this issue to all types up to those defined in `Mina_transaction`. I'll open a new issue for the other ones.
