### ISSUE TITLE
ppx version linter changes

### ISSUE THREAD

**Issue by p-shahi** [MinaProtocol/mina#11181]
Acceptance criteria: 
- script that enforces lint needs to be updated
- change ppx version code that's used by linting script

**Comment by psteckler** [comment]
The OCaml side of this is done.

In CI, the linter script should:

- download Docker images for the release branch, PR base branch, and PR branch.
- in each image, run `mina internal dump-type-shapes -max-depth N` (where `N` is maybe 5)
- that prints out a path to a type, a hash of the type shape, and the type shape as an S-expression, to the given depth
- in a Python script, create dictionaries for those 3 dumps; the path can be a key, and the hash and shape the value

We can get Docker images for each branch. After checking out a branch, the following command gets a 7-digit hash:
```
git log -n 1 --format="%h" --abbrev=7 --no-merges
```
For each branch, pull the Docker image `minaprotocol/mina-daemon:<hash>-stretch-mainnet

For every `query` and `response` type in the release branch, that same type exists in the PR branch, and hasn't changed shape (can just compare the hashes to detect changes); that assures old RPC versions are still supported

For every type `t`, `query`, and `response` type in the PR branch, if the hash differs from the hash in the base branch AND differs from the release branch, the type has changed. But we only issue a warning, and have the linter fail, if the PR branch type shape differs the depth-limited type shapes in the release and base branches. So, check the hashes first, then check the shapes. Print the 3 hashes and shapes if there's a failure.

The reason for depth-limiting the output is that a type shape includes the shapes of contained types. If a containing type has not changed, but only its contained types, we don't want to report a failure related to the containing type. 
Some experimentation is needed to know what the appropriate depth `N` is, so that we don't see differences when a contained type has changed, but we do detect all differences in the immediate type.

Once this is working, the directory `src/lib/ppx_version/tools/` can be removed.

**Comment by Smorci** [comment]
Currently the above mentioned implementation seems unreliable. Numerous commits do not trigger the CI step for creating a docker-mina-daemon image, thus there is nothing to pull from Docker Hub.

One possible solution would be to use Nix in the following way:

- checkout the commit from the branch
- create the docker image with Nix
- start a container, enter and retrieve paths to types

The advantage of this solution would be that we don't rely on the succession of any CI. Which ideally wouldn't even be an issue, but currently we have two CIs and people tend to merge PRs indifferently of the result.

**Comment by Smorci** [comment]
Finished the development of the linting script ([branch](https://github.com/MinaProtocol/mina/tree/ppx-lint-script)). Until the Nix CI is migrated to the Mina Foundation infrastructure, this issue is on stand by.

**Comment by michal0mina** [comment]
@Smorci please create one liner to run it locally as well (not only in the CI)

**Comment by Smorci** [comment]
To run the script locally you need to:

-  checkout the [ppx-lint-script branch](https://github.com/MinaProtocol/mina/tree/ppx-lint-script)
- run `nix build .#ppx-lint`
- then run the script living in `result` and pass the branches as arguments (e.g. `./result/bin/ppx-lint --PR-branch <PR-BRANCH-NAME> --base-branch <BASE-BRANCH-NAME> --release-branch <RELEASE-BRANCH-NAME>`

If you encounter any issues reach out to me.

**Comment by psteckler** [comment]
```
$ ./result/bin/ppx-lint --PR-branch develop --base-branch develop --release-branch develop
Traceback (most recent call last):
  File "/nix/store/pp6wykv47iplcmn85nm4gdsw4nk7zscv-lint_ppx.py", line 95, in <module>
    branches = [args.pr, args.base, args.release] 
NameError: name 'args' is not defined
```

**Comment by psteckler** [comment]
There should be a test suite that covers the various cases. That could run in CI, maybe not necessary.

**Comment by psteckler** [comment]
In Google Cloud, I see images for non-merge commits in `develop` at:
```
gcr.io/o1labs-192920/mina-daemon:<commit-sha>-bullseye-mainnet
```
The two most recent non-merge commits don't have an associated image, but I think those were merged without CI running. 

The Dockerhub repo does not appear to be getting updated.

You can run:
```
git log -n N --format="%h" --abbrev=7 --no-merge
```
for a big enough N to find the most recent image.

**Comment by psteckler** [comment]
Looking at the script, the output contains the text "has hash" when it's printing the shapes.

To work in CI, the script needs to exit with a nonzero code if there's a versioning error. I don't see that in the script.

**Comment by psteckler** [comment]
The script is using a max-depth of 5, which might work. Did you experiment with other depths?

We want the largest depth that reveals differences in containing types, without revealing differences in contained types.

**Comment by psteckler** [comment]
I wrote some code in branch `feature/new-version-linter` that downloads the Docker images and dumps the type shapes.

**Comment by psteckler** [comment]
The Python script in that branch is ready, it just needs integration into CI.

**Comment by Smorci** [comment]
The code looks good, but personally I would rather rely on Nix building Mina and getting the dump than relying on the current state of the CI (I still think there might be some Docker images missing). I cannot say for sure that this is true, I just know that with Nix there wouldn't be this dependency, and it does exactly the same thing. Did you do testing with your script?  

The error from my script that you mentioned, is an easy fix, I declared the variable `args` after the invocation, my bad.

I haven't experimented with `max-depth`. We could make it a parameter and start testing different values.

**Comment by Smorci** [comment]
Isn't the integration done with this [dhall file](https://github.com/MinaProtocol/mina/compare/develop...feature/new-version-linter#diff-281a7202d4f8f6a84ec8bfa0bd6b0dda19e74408d988d2fb817455451ab6b8fe)?

**Comment by psteckler** [comment]
> Did you do testing with your script?

Yes, it was able to download a Docker for the latest merge into `develop`. There is more testing to do, though.

> Isn't the integration done with this [dhall file]

No, it's not working. Andrew has promised to help.

**Comment by psteckler** [comment]
Looking into adding the printed representation of the type, besides the shape, for the output.
