### ISSUE TITLE
"merges cleanly into compatible/develop" script imperfect

### ISSUE THREAD

**Issue by yorickvP** [MinaProtocol/mina#11206]
While merging https://github.com/MinaProtocol/mina/pull/11173 and https://github.com/MinaProtocol/mina/pull/11174, CI passed on 11173 while it shouldn't have, and then didn't pass on 11174 while it should have.

**Comment by robinbb** [comment]
@yorickvP @kantp Since the knowledge about this is possessed by Yorick, and because it fits squarely into the theme of the other work with the Tweag label, we should accept this work into the backlog. @yorickvP does it not make sense to correct this promptly to avoid false negatives and false positives on PRs?
