### ISSUE TITLE
`Cancelled status for parties that were skipped due to failures in another party

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#11628]

**Comment by ghost-not-in-the-shell** [comment]
When applying a zkapp transaction, we accumulate failure status for failed account updates, and when it hits a failure case, none of the account updates are applied except the fee payer. For those account updates, we should put a `Canceled` status so that it's clear they are not applied.

Implementation plan: In `mina_transaction_logic.ml`, we checks all the updates. If we find a failure, then we just iterate through the failures and pop up the `Canceled` status for every account updates.

**Comment by deepthiskumar** [comment]
https://github.com/MinaProtocol/mina/pull/11942
