### ISSUE TITLE
Split Nix CI to run on multiple machines

### ISSUE THREAD

**Issue by balsoft** [MinaProtocol/mina#11892]
Currently, Nix CI runs on a single runner, and can't be easily scaled due to the way it is structured (the generated pipeline references derivations, which may not be available on machines other than the one that the pipeline was generated on). Fix this by making a derivation cache.

**Comment by balsoft** [comment]
Work in https://github.com/minaprotocol/mina/tree/nix-ci-scalable-runners

**Comment by robinbb** [comment]
@balsoft Can you point to the PR that delivers this work?

**Comment by robinbb** [comment]
@mzajda0mina Please follow up.

**Comment by mzajda0mina** [comment]
Update after talking with Alex

Needs low level NIX work to replace default work distribution.
1. We are not using "remote builder". Reliability reasons. 
2. We have multiple servers that communicate via shared cache
3. Shared cache protocol: copying derivations was extremely slow due to sequential processing big numer of small files
4. Alex intends to replace native derivations protocol with copying it by hand (one large file = fast)

@balsoft please follow up with details when you have chance

**Comment by michal0mina** [comment]
deployed to google cloud (tweag)

**Comment by balsoft** [comment]
The approach with multiple agents, all uploading derivations to a shared cache and then downloading them as needed has problems:

- Just naively uploading/downloading derivations takes a really long time due to the very inefficient way that Nix handles them;
- Bundling all the derivations together, and then uploading/downloading them is
  1. Hacky
  2. Results in much more complicated and ugly pipeline generation

So, for now I set it up using remote builders. This mostly works, but there's also a bug which leads to some builds hanging indefinitely sometimes. I knew about this bug (hence "reliability concerns"), but I have not managed to track it down yet. This does not happen too often, but is annoying. However, it mostly works.

**Comment by michal0mina** [comment]
We have distributed setup now -- closing ticket.
Also we have more insight about the parallelism bug which hits Nix (agent+N*builder setup).
Non bug scenerio is documented in Nix performance raport in Notion.
Deployment architecture is documented in Nix-Ci Notion page.
