### ISSUE TITLE
Create separate alert channels for networks

### ISSUE THREAD

**Issue by amc-ie** [MinaProtocol/mina#11933]

**Comment by amc-ie** [comment]
At present our #testnet-warnings channel contains too many sources which renders it noisy and difficult to tell high priority items from others. We need to have separate channels for MainNet, Devnet and Berkeley that display only the corresponding alerts from their respective network monitoring.

Acceptance criteria:
#mainnet-warnings #devnet-warnings (can use testnet) and #berkeley-warnings are created and are displaying only the alerts associated with their respective network deployments.

**Comment by stevenplatt** [comment]
Alerting rules appear to be getting triggered by a linking between Slack and Grafana. 

Configuration for this alerting appears to be located here:
https://o1testnet.grafana.net/alerting/list

Splitting out the alerting may be possible by creating a new Slack channel, and setting a new alert rule that is more narrowly targeting a single testnet (perhaps by its literal name, rather than a broader regex). 

Documentation for the Grafana alerting functionality can be found here: https://grafana.com/docs/grafana/latest/alerting/
Looking into this now.

**Comment by stevenplatt** [comment]
This item is completed. The steps to edit the alerting are as follows:
- Create a new slack channel and webhook to allow messages into the channel (https://www.jajaldoang.com/post/create-grafana-alert-slack/)
- Create a new alerting "contact point" within Grafana
- Create a new alerting "notification policy" within Grafana
- Test everything by waiting for alerts to come in. 

Adding new "alert rules" were not required, as these were already defined. The alert rules set the individual items that trigger an alert. The changes done above are using the existing alert rules and changing where they are sent (to new slack chanels).
