### ISSUE TITLE
Add tests for nix .deb packages to ensure that version output contains a valid commit hash

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#11976]
Pull request https://github.com/MinaProtocol/mina/pull/11838 is attempting to add a hack for nix builds that skips generating the commit information at build time. This information is used by the mina CLI for errors and the version command. The information is valuable for debugging issues and determining which versions introduced or resolved bugs.

It would be good to add a simple check that ensures that the `.deb` package generated from by nix correctly embeds this information in the binary, ie. to make sure that this hack is only applied to dev builds. This can be done by running `mina.exe -version` after installing this package.

**Comment by balsoft** [comment]
We have a couple of options to test this inside a derivation:

1. Install the package inside the sandbox
2. Run a podman container, install the package in it, run there
3. Run a VM, install the package there, run there

(1) doesn't work ATM because the package contains `/nix/store` on its own and so can't be installed on the host, (2) doesn't work because user namespaces are disabled inside the sandbox, (3) is really slow. I propose we postpone implementing this until the deb package is improved and (1) is feasible.
