### ISSUE TITLE
Deploy upgraded mainnet archive nodes with more storage and future-proofing

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#12242]

**Comment by stevenplatt** [comment]
This item has been completed. A new `archive-4` has been deployed to mainnet, using a 100GB local disk. 

Because this is a manual configuration, the source code has not been merged into the main repository, but is stored in a branch within `mina-deployments` named `mainnet-archive-4`.

A diff of the changed made for the deployment are located here: https://github.com/MinaProtocol/mina-deployments/commit/5e941946e6061221abc0c394158f2bedce8888eb

An update version of these settings will be used as part of migrating the mainnet servers from the O(1) gcloud instance, into a new Mina Foundation project and will be merged when that work is complete.
