### ISSUE TITLE
[Transaction Pool] - Duplicate zkapp cmd nonce fee payers are not removed

### ISSUE THREAD

**Issue by MartinMinkov** [MinaProtocol/mina#12384]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

The transaction pool has logic to remove zkapp commands that are submitted that have duplicate nonce values from the same fee payer. Say we construct the following zkapp commands:

1. Fee Payer Keypair, with nonce value of 0 and fee of `10_000_000_000`
2. Fee Payer Keypair, with nonce value of 0 and fee of `20_000_000_000`

If we submit these zkapp commands into the transaction pool, we would expect the first to be removed and the second to be the one that is left. _This is not the case however_, if the second fee payer as a fee equal to or greater than the previous zkapp command, the transaction pool contains the two zkapp commands. IF the fee is lower than the previous zkapp cmd, then the second one is removed (which makes sense).

So in the case where the fee is greater with the same nonce, the first should be replaced but instead both are kept in the transaction pool.is

### Steps to Reproduce

I have created a branch that can reproduce this behaviour. 

See the following link here: https://github.com/MinaProtocol/mina/pull/12383/files#diff-163dbe21d215ac37560cd6328ade1c05a5e607d13164e12a5f6de07a73dc37cbR2639

To reproduce:

1. Check out to `reproduce/transaction-pool-nonce-zkapp`
2. Run the transaction pool tests -- `./scripts/testone.sh src/lib/network_pool/transaction_pool.ml`
3. View results

### Expected Result

The expected result should be that only the second submitted zkapp command should be in the transaction pool

### Actual Result

The returned result shows that both submitted zkapp commands are in the transaction pool, and the test fails.

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Medium

### Status

```shell
NA
```

**Comment by bkase** [comment]
Note: this happens for regular payments too, not just zkapp commands

**Comment by bkase** [comment]
Note: This only happens if you add these commands _at the same time_ in the same diff

**Comment by bkase** [comment]
I suspect, but am not 100% sure yet, that there is a similar error happening here that we saw with the verification key bits. There is something that is "read" at a state at the beginning of diff application that doesn't update as the diff is being applied.

However, rather than continuing to dig and adding logic to support this -- further complicating the transaction-pool and/or indexed-pool, can we instead just pre-process the diffs to pick the largest fee for duplicate transactions (of the same nonce)?

**Comment by bkase** [comment]
Latest information on this:

1. Make sure you start from Martin's repro and reduce from there. Be 100% sure you're still reproducing the bug as you move forwards. I lost some time going down a wrong path by not being careful of this. It _could_ be the case that actually this only happens with zkapp commands and not payments, but not 100% sure
2. We do want to dig into the logic for the txn pool -- and specifically it's important that this happens in the `apply` function since we want to make sure the world doesn't shift from underneath us as we're processing data. I recommend building the solution on top of https://github.com/MinaProtocol/mina/pull/12380 as there are several changes to the txn pool there.
3. In addition to fixing this failing test directly, it's also important to fix the way we handle stacked nonces from the same fee-payer; right now Nathan claims the transactions being sent around are bundled into a hashmap and the order sorted by nonce is forgotten. We should modify the keys of the table to include the nonce in them so we don't forget that order (so something like `account_id of fee-payer * nonce` as the key)
