### ISSUE TITLE
Port changes to rosetta-sdk-go to our own fork

### ISSUE THREAD

**Issue by kantp** [MinaProtocol/mina#12438]
We are currently using a modified version of `rosetta-sdk-go` for testing of constructing transactions invoving delegations. Those modifications are currently in https://github.com/ylecornec/rosetta-sdk-go, but we want to have them in https://github.com/MinaProtocol/rosetta-sdk-go.

**Comment by kantp** [comment]
@kaozenn said that https://github.com/MinaProtocol/rosetta-sdk-go seems to have some changes that are incompatible with the main repository at https://github.com/coinbase/rosetta-sdk-go, so the first task here will be to look at whether those changes are still relevant.

**Comment by Sventimir** [comment]
Indeed, https://github.com/MinaProtocol/rosetta-sdk-go is no longer compatible with the main repository. There are 3 commits made in August 2020 and the repository seems to not have been updated ever since. It can be realtively easily rebased, but I think MinaProtocol/master should always reflect the main-line master. Therefore I'll rename the main branch and rebase it in case anyone needed it still (which I don't think is likely). Then I'll sync our master with the main-line. Finally, I'll clone Yves-Stan's work to yet another branch in our repo.

**Comment by Sventimir** [comment]
In fact it seems that these commits were actually integrated into the main-line, albeit with some modifications.

**Comment by Sventimir** [comment]
I renamed the stale `master` branch to `master-old`. I then set `master` to follow the main-line repository. Finally I cloned Yves-Stan's branch as `pallas_signer_stake_delegation`. It follows Yves-Stan's branch, but  that is unlikely to change in the future. However, we might need to make some changes to it in case Coinbase requests it. In that case we won't be able to change Yves-Stan's code. I'm also not sure if we'll be able to replace his branch with ours in the existing PR. Maybe it'd be the easiest to close that PR and reopen our own?

**Comment by kantp** [comment]
Yes, that sounds like a good idea!

**Comment by Sventimir** [comment]
The new PR meant to replace the one by Yves-Stan: https://github.com/coinbase/rosetta-sdk-go/pull/464.
