### ISSUE TITLE
Initial verification of custom gates in wrap proofs

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#12486]

**Comment by mrmr1993** [comment]
The [`Wrap_verifier.incrementally_verify_proof`](https://github.com/MinaProtocol/mina/blob/a3661e44e01b2c400d6eb5ac254c6ab7a91b3623/src/lib/pickles/wrap_verifier.ml#L501) function is responsible for starting the verification of a step proof, which the finalization code then, well, finalizes. In order to do this, we will need to:
* pass in the feature flags to this function, so that it knows which feature set it's verifying
* pass them onwards to [`Common.ft_comm`](https://github.com/MinaProtocol/mina/blob/a3661e44e01b2c400d6eb5ac254c6ab7a91b3623/src/lib/pickles/wrap_verifier.ml#L662)
* update [`Common.ft_comm`](https://github.com/MinaProtocol/mina/blob/a3661e44e01b2c400d6eb5ac254c6ab7a91b3623/src/lib/pickles/common.ml#L241) to add the scaled commitments for each of the new gates (optionally, depending on the state of the flags).
* in order to do this, you'll probably need to update [`Plonk_verification_key_evals.t`](https://github.com/MinaProtocol/mina/blob/a3661e44e01b2c400d6eb5ac254c6ab7a91b3623/src/lib/pickles_types/plonk_verification_key_evals.ml#L8) to have the optional commitments for the new gates
  - in turn, you will then have to route the data through from the rust bindings to feed into them
  
There are a few other things (e.g. combined_inner_product, which probably needs updating in OCaml *and* in rust -- I think it's in `verifier.rs`), but hopefully those will become obvious from the verification errors that present themselves once you try to wrap a proof using the gates. If this is not obvious, @ me.

**Comment by mrmr1993** [comment]
Note: the flow of logic should be similar to that in `verifier.rs` in kimchi, so it will most likely be helpful to compare the two, to see which optional steps (in the rust) are currently omitted in the OCaml circuit, and to add them.
