### ISSUE TITLE
Plan for devnet and mainnet archive DB migration

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#12676]

**Comment by psteckler** [comment]
Items to consider:

- incremental migration
- change in txn hashes
- adding default token
- account ids instead of public keys for user commands
- global slot vs. global slot since genesis 
- populating accounts_accessed and accounts created per block

**Comment by psteckler** [comment]
More details.

- Incremental migration is desirable so we can migrate the bulk of the db well before the hard fork, and do the last slots just before. The migration app can examine the target db, look for the maximum height, start at next height. Do we wish to migrate blocks that are not marked as `canonical`?

- The Base58Check version byte has changed for transaction hashes, making them distinguishable from the existing hashes. The hash is now calculated from the `Bin_prot` serialization of signed commands with dummy signatures, where the hash used to be calculated from the Base58Check serialization with no change to the signature.

- We can add the default token, the only token that exists on current mainnet. Signed commands and internal commands when migrated will not mention the token, it's implicitly the default.

- At migration, the `global_slot_since_genesis` won't change. And `global_slot_since_hard_fork` also won't change at this migration, or future migrations, because that's the slot relative to the hard fork in which the block was created. In this case, that "hard fork" is genesis itself.

- The migration tool should replay transactions to obtain the new accounts to populate the `accounts_created` table; the result of applying a command includes the new accounts created . That information is also available in the `blocks...command` tables via the creation fee columns. But we'll want to replay the transactions to validate the db contents. In fact, we should check that the creation fees in the existing db match the new accounts created.

- Getting the last VRF output and subwindow densities will require importing precomputed blocks for just those fields. We can leave those columns NULL during the migration, and write an app to import just those fields.

**Comment by psteckler** [comment]
Columns in mainnet archive db changed after migration:
- user_commands.hash (calculated differently, different Base58check version byte)
- internal_commands.hash (ditto)

Columns that will be removed:
- timing_info.token (because always the default token)

Information moved to `accounts_created` table:
- blocks_user_commands.fee_payer_account_creation_fee_paid
- blocks_user_commands.receiver_account_creation_fee_paid
- blocks_internal_commands.receiver_account_creation_fee_paid

Columns that are preserved, but can't be checked after migration:
- blocks.ledger_hash
- blocks.snarked_ledger_hash
- epoch_data.snarked_ledger_hash

The `balances` table is deleted, and so are columns referring to it. Balances will be available from `accounts_accessed` table.

**Comment by deepthiskumar** [comment]
[Schema diff](https://github.com/MinaProtocol/mina/compare/compatible..berkeley#diff-2638a4585d68f08023365f7df8bff3cebdd12aeffbb27dc2cdc54816e17f50a0)
1. Indexes removed: Drop all the indexes removed

2. Tables removed: Drop the tables removed
```
balances
```
3. Updates to existing tables
 
    a. `timing_info`
    ```
     1. Populate account_identifier_id column based on public key and default token
     2. remove deleted columns 
     3. update column data types
    ```
     b. Rename table `user_command_status` to `transaction_status`
     c. `user_commands`: Rename column name and update column data types
     d. `internal_commands` :Rename columns name and remove columns
     e.  `epoch_data`: New columns added, insert data for those from precomputed blocks as @psteckler mentioned above
      f.  `blocks`: New columns added, insert data for those from precomputed blocks
      g.  `block_user_commands`: Rename column name and update column data types
      e.  `blocks_internal_commands`: Remove columns and for the new columns-
      ```
      1. status: All mainnet internal commands are `applied`
      2. failure_reason: None/empty  
      ```
4. New tables added that need to be populated with existing data

    a. `token_symbols`: Insert default token ID
    b. `tokens` ; insert default token ID with no owner
    c.  `account_identifiers`: For each public key in `public_keys` insert a row with the default token
    d.  `voting_for`: Insert default value
    e.  `protocol_versions` :  Insert current version and new version for berkeley
    f.  ` accounts_accessed`, `accounts_created`: Replay transactions on genesis ledger and populate this table as @psteckler mentioned above.

5. Change in hashes and any other data: I'm proposing **no** changes be made to any historical data
    a. `user_commands.hash`: calculated differently in berkeley, different Base58check version byte. The changes are captured [here](https://github.com/MinaProtocol/mina/issues/11505). Need confirmation on whether any migration is needed for this field and if so, why (I'd like to better understand this so that we can come up with appropriate solutions)?
    b. `internal_commands.hash`:  Same as user_commands.hash
    c. `blocks.ledger_hash`
    d. `blocks.snarked_ledger_hash`
    e. `blocks.state_hash`
    f. `blocks.parent_hash` 
    g. `epoch_data.snarked_ledger_hash`

6. Exceptions: 
   a. `accounts_accessed.receipt_chain_hash` for existing accounts will be different on berkeley. @psteckler  was the plan to populate `accounts_accessed` table using mainnet replayer version or berkeley? If we are okay with  preserving historical data (bullet point 5), then we should consider using the mainnet replayer and populate default values for new columns

**Comment by deepthiskumar** [comment]
#10781 #12331

**Comment by psteckler** [comment]
> was the plan to populate accounts_accessed table using mainnet replayer version or berkeley

We'll need a modified replayer to populate that table. I was thinking that replayer would work on the otherwise-migrated data, so it would be modified from the berkeley replayer.

**Comment by psteckler** [comment]
Modified `berkeley` replayer to add `account...` tables in branch `feature/add-berkeley-account-tables`.

The app does everything the replayer does, plus populates those tables, so it validates the migrated data.

**Comment by psteckler** [comment]
>  If we are okay with preserving historical data (bullet point 5), then we should consider using the mainnet replayer and populate default values for new columns

The app is a modified `berkeley` replayer, which is able to populate all the columns of `accounts_accessed`.
