### ISSUE TITLE
Prevent replay attacks on Control Graphql's authentication

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#12885]
Security of the control graphql as described in issue #12811 has a drawback: a request formed by the Orchestrator and sent to one node can be taken by it and sent to another node, thus making a successful replay attack.

A proposed flow that allegedly removes the replay attack possibility:

1. In auth endpoint return an UUID unique for the Mina node's launch (i.e. new with every restart, but same if the node continues running)
2. In payload of every mutation and query include the UUID and the sequential identifier of the request
3. Assume sequential identifier of request to increment with every request from the same `pk` (i.e. triple `uuid, pk, sequential_id` is unique across all requests to all nodes), where `pk` is Ed 25519 public key of the Orchestrator

**Comment by psteckler** [comment]
The Ed25519 public key is made available in the `Authorization` header. The HTTP headers are not passed to the GraphQL code that services queries and mutations.

Can I suggest that the UUID, sequence no. pair be also placed in a header, maybe called `Sequencing`, rather than in the GraphQL requests? That way, we don't have to change any of the GraphQL query and mutation code, and we won't forget to add the sequencing check.

The HTTP code will need to know about the `auth` request, and not do the sequencing check for that particular query.
Maybe we need to add something like a ` currentSequenceNo` request.

**Comment by georgeee** [comment]
@psteckler I agree with your idea, but I would suggest adding these to `Authorization` header (just a few more items separated by spaces)

**Comment by georgeee** [comment]
> > I would suggest adding these to `Authorization` header
> 
> Proposed format for Authorization header:
> 
> ```
> Signature the-pubkey the-signature ; Sequencing the-uuid the-sequence-no
> ```

Sounds good
