### ISSUE TITLE
Restrict account permissions for verification key updates

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#12907]
Disallow setting "proof only" and "impossible" permissions on the verification key of accounts.

**Comment by deepthiskumar** [comment]
* check permission for verification key is not `Proof` or `Impossible` in zkapp_command_logic.ml (common code for both in-snark and outside snark computation)
* New failure status for the same
* Update tests (the tests with Proof and impossible auth permission should now fail with the new failure status)
* Nothing to handle in transaction pool because we don't check account updates in the pool

**Comment by mrmr1993** [comment]
We took a different approach for this. Closing.
