### ISSUE TITLE
--max-connections limit does not works properly

### ISSUE THREAD

**Issue by c29r3** [MinaProtocol/mina#13288]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/MinaProtocol/mina/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/MinaProtocol/mina/discussions

### Description

`--max-connections 50` look at the graph with a forced limit on the maximum number of connections  
Version: `1.3.1.2-25388a0-focal-mainnet `
<img width="1354" alt="image" src="https://github.com/MinaProtocol/mina/assets/52304443/36b81965-7306-41e3-813d-1eab62d8e795">

### Steps to Reproduce

1. start node with flag `--max-connections 50`
2. look at the graph of connections in monitoring

### Expected Result

Number of active peers about 50

### Actual Result

32-100

### How frequently do you see this issue?

Always

### What is the impact of this issue on your ability to run a node?

Medium

### Status

```shell
A large number of connections can lead to OOM
```

**Comment by vanarasiantonyswamy** [comment]
Investigation was done.

**Comment by vanarasiantonyswamy** [comment]
At certain moments there might be spikes.
There might be a **few connections per peer**, although most of the time it's at most one.
if you see a plot where you just see growth always climbing up and never coming down, its an issue then. Since this graph shows the Peers showing drops its not an issue.
I ran the Testing and saw the connections dropping and climbing for the peers. Closing this issue. please reopen the issue if you see the graph climbing and not coming down.
