### ISSUE TITLE
Gossipping transactions is a defect-defect equilibrium

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#1340]
Block proposers get fees from transactions and need SNARKs to do so. So they have an incentive to collect as many (profitable) transactions as they can and prevent other proposers from doing the same. If Alice gossips a transaction to Bob and Bob's next slot is before Alice's, then Alice just lost money. The optimal strategy is to defect - receive gossip messages but not forward them. At least so long as the gain from increased fees exceeds the loss from the protocol being less valuable due to increased transaction times and/or transactions not being mined at all. The value of the protocol is a [commons](https://en.wikipedia.org/wiki/Tragedy_of_the_commons), even with PoS, so we should expect defection to be the optimal strategy, at least so long as the proposer's stake is relatively small.

I originally thought gossipping should be done on a [Tit-for-tat](https://en.wikipedia.org/wiki/Tit_for_tat) basis. But this is complicated by block timings: if we're doing tit-for-tat and Alice has the current slot, she should gossip everything she knows, since no one can mine those transactions before her, and collect credit on those transactions to get future ones. The transactions she gossips immediately before her block is published are valueless to anyone else. So this requires at least a little more thought. I'll know more after I understand Ouroborus better.

**Comment by es92** [comment]
There's a fair bit of resources online discussing this, here's one - [stack exchange, what-forces-transactions-to-be-visible-to-all-miners](https://bitcoin.stackexchange.com/questions/54050/what-forces-transactions-to-be-visible-to-all-miners/54052)

Fortunately its not too bad because senders can choose who / how many ppl to send a transaction to. I have some thoughts on this as well on what would develop in a truly adversarial environment (I think it would be fine basically, just with individual miners setting up more structures and connections to ensure something like tit-for-tat would happen).

Note also that everyone is still incentivized to broadcast blocks / the blockchain so this doesn't challenge correctness but just adds some complexity to the relationships between participants / miners.
