### ISSUE TITLE
Snark coordinator falls into catchup/bootstrap too frequently

### ISSUE THREAD

**Issue by georgeee** [MinaProtocol/mina#13453]
Snark coordinator falls into catchup/bootstrap too frequently

Cause: some transitions take 100-300s on step of notifying the "best_tip_diff" frontier extension.

**Comment by deepthiskumar** [comment]
comments from @georgeee 

Snark coordinator (connected to 20 workers on a cluster with 30s window and k=12) falls into catchup/bootstrap every few minutes
This happens within handling of best_tip_diff extension
The trouble was in (indirect) locking on a broadcast message sending on IPC layer
I applied two fixes: [don't block on rebroadcast](https://github.com/MinaProtocol/mina/pull/13036/commits/a9a320941242f20dcf3ad90d83e8a43460c3fd18) and [remove mutex lock in snark pool](https://github.com/MinaProtocol/mina/pull/13036/commits/ded01a4bdb9f4192e6c61b76c4775b91760879b2) . Both of them fixed the issue. Maybe the former would be sufficient. However I'd include both as the latter removes an unnecessary functionality and simplifies code

The issue is due to 30s block window. Extension adds a sizeable delay (~100s-300s), but with 3-min window there won't be a cumulative effect. Real trouble in this issue is that one block takes 100-300s, a queue of blocks accumulate meanwhile. And then another from the queue takes 100s-300s. This won't happen with block window of 180s, so to say
