### ISSUE TITLE
Deploy proof-of-concept Grafana dashboard with PR/CI metrics

### ISSUE THREAD

**Issue by stevenplatt** [MinaProtocol/mina#14262]
# Summary

This task is to document the deployment of a proof-of-concept dashboard which will display metrics relating to shipping code within O(1)Labs. This prototype dashboard is not intended to be complete, rather to demo the variety and types of data that can be parsed and presented. For the initial POC, the data is limited to the `mina` repository and the Buildkite CI system. It does not include repositories for infrastructure, o1js, or repositories maintained by Mina Foundation.

## Requested dashboard items

Note that the metrics dashboard is intended to show activity retroactively and is not intended for use in realtime debugging or for showing live status. 

For the initial proof-of-concept, the following metrics are requested, and are split into two categories:

**Github PR metrics**

- [x]  Total open pull requests (per day): What is the trend and direction of open pull requests?
- [x]  Average number of CI runs per open pull request: Does the average pull request run CI once or multiple times?

**Buildkite CI metrics**

- [x] Overall CI reliability
- [x] Total CI builds (per day): How many builds is CI completing in a day?
- [x] Average time per build (per day): How long does each build take, on average?
- [x] Average test fails per successful build (per day): For tests that eventually pass, how many retries are needed on required tests?

### Measuring CI Reliability

Currently, in the context of CI, reliability is defined as: 
_“Tests reach a valid pass or fail state, without developer intervention”._

The calculation of this is:

**reliability = ((total CI runs - successful CI runs with greater than n retries) / total CI runs) * 100**

Related slack thread on CI reliability: [Slack Thread](https://o1-labs.slack.com/archives/C04QQPPEYBF/p1696510461185709)

**Comment by SanabriaRusso** [comment]
I have created a placeholder for the CI Dashboard in branch "[luis-ci-dashboard](https://github.com/MinaProtocol/mina/tree/luis-ci-dashboard)" at the Mina repo.

You may head over there to check any updates. I will keep this thread open and updated with the progress.

**Comment by SanabriaRusso** [comment]
The [most recent commit](https://github.com/MinaProtocol/mina/commit/34ffffd70726fea1c9f28afbb75af518194a75e6) proposes an initial scaffolding for triggering and pre-processing metrics.

Relevantly, it imports Python scripts from a directory "**/files/{github | buildkite}/example.py**" into a ConfigMap. This is mounted as a Volume into the corresponding "retriever" container, which executes via bash as entrypoint. This workflow allows for independent development of the Python scripts and the Helm Chart.

**Current state**: GitHub retriever script pulls branches from "mina" repo and pre-process them. In order to replicate such test a valid Fine-scoped GitHub Token is enough.

There are still elements **to be developed**, these are:
- Precise list of queries satisfying this issue's requirements
- Storage backend: this was removed in the most recent commit as to keep branch HEAD in sync with state of development.
- Population of such storage backend with each run of the CronJob.
- Import Storage backend as Grafana datasource
 
Updates will follow development.

**Comment by dkijania** [comment]
Implementation of buildkite metrics is in PR: https://github.com/o1-labs/bk_analysis/pull/1. I've added missing stuff to Joseandro script. It produces json which then can be easily transformed into any data source

**Comment by SanabriaRusso** [comment]
In the most recent commit to the [ci metrics dashboard](https://github.com/MinaProtocol/mina/tree/luis-ci-dashboard/helm/ci-dashboard) we are now able to push pre-process metrics to the local DB instance.

The two GitHub metrics are retrieved using GraphQL API by a retriever, which writes the result to a text file. After all retrievers are done (at the moment there is only GitHub's), the main DB Pusher container will establish a connection to the local DB and insert such values in a dummy table.

The workflow seems to be working OK. Next steps will be to include @dkijania 's code, filter the metrics we want and then recreate the same workflow.

**Comment by SanabriaRusso** [comment]
[Retrievers are deployed](https://github.com/MinaProtocol/mina/tree/luis-ci-dashboard/helm/ci-dashboard), At this moment the CronJob is configured to run every 5 minutes, populating the database with enough data so the Grafana dashboard could provide some default information.

**Comment by SanabriaRusso** [comment]
A draft CI Metrics Dashboard for the PoC is [available](https://o1testnet.grafana.net/goto/JjFLiNVSR?orgId=1)

**Comment by stevenplatt** [comment]
This item has been completed. Closing the corresponding zenhub issue.
