### ISSUE TITLE
Address yojson error due to o1 trace changes

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#14629]

**Comment by nholland94** [comment]
The actual issue here isn't a problem with the yojson error, but rather, with how we are reporting errors in general.

#14397 was landed, and while it did surface some errors that were previously being hidden, it's also had the side effect of accidentally bundling unrelated stacktraces with errors that are raised from o1trace threads. I believe this has to do with the way async tracks backtraces, and async will cache the last backtrace that was ever thrown from a thread, even if that backtrace was caught. There may be some unexpected interplay with execution context that is relevant here in order to access the correct backtrace.
