### ISSUE TITLE
Allow deserializing subfields of composed data structure like records and tuples.

### ISSUE THREAD

**Issue by rbonichon** [MinaProtocol/mina#15184]
Instead of deserializing the entire data, it should be sometimes more efficient to just look at particular subfields, e.g., when iterating over encoded data to access only a known sub-element.

Ideally, resolving this issue would enable a `[@bin_fields]` annotation for data structures supporting such a feature.
This annotation is to be supported by a `ppx` that would somehow combine  [`bin_prot`](https://github.com/janestreet/bin_prot) and  [`fields_conv`](https://github.com/janestreet/ppx_fields_conv).

**Comment by emberian** [comment]
bin_prot isn't easily seekable, but there could still be some kind of work to be saved here allocating temporary objects, and using the shapefile to guide deserialization instead of generated code. depending on how good ocaml gc is at young object nursery and traversing shapefile vs running code, i could see this being a bunch of complexity for extraordinarily marginal gain.

are there concrete callsites that we know to be slow and can use as index to measure the maximum gain to speedup from any improvements here?
