### ISSUE TITLE
Make a proposal for semantic versioning

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#2747]
Examples: 
- Elm 
- Anything HashiCorp

**Comment by enolan** [comment]
Some stuff to keep track of: there are three kinds of updates to cryptocurrencies.

* Client updates that don't touch the network protocol at all. These don't require any kind of coordination across nodes.
* Client updates that modify the protocol in a way that doesn't affect the underlying consensus/state machine system. E.g. if we change something about how the gossip systems work or add new rpcs. These changes should be backwards compatible and handled via protocol negotiation. They don't *need* coordination, but you won't get any benefit out of them if nobody is speaking your language.
* Updates the *do* modify consensus/state machine semantics. This is anything that e.g. changes PoS, adds new user commands/transactions, modifies existing ones, and for Coda, anything that changes the SNARK circuits. **These need to be coordinated in advance, and start at a specific slot number**. Since every node must see the same network state and unupgraded nodes will not accept blocks using the new changes, we have to wait to start using the new stuff until all network participants have had sufficient time to upgrade, and begin at exactly the same time. These kind of upgrades are called *hard forks*. If we decide on the hard fork schedule in advance we can have unupgraded clients die with an error message at the specified slot time. If we don't, or there's an emergency requiring a hotfix, unupgraded clients will end up partitioned from the main network.

[Here](https://www.etherchain.org/hardForks)'s a list of Ethereum's hard forks. [Zcash](https://z.cash/upgrade/) has hard forked twice with a third planned for October.
