### ISSUE TITLE
Optimizations for libff

### ISSUE THREAD

**Issue by enolan** [MinaProtocol/mina#2759]
While working on updating the staged ledger tests to use real commands and ledger I ran into some pretty serious performance issues.

[Here](https://drive.google.com/file/d/1yNlJJyEESDyjdczjGZWlHJOxhvaRkRQg/view?usp=sharing)'s a profile. Decompress it and load it into https://www.speedscope.app. `perf` profiles are kind of weird, that's the best way of reading them I've found. Click on "sandwich" to see an ordered list of cost centers. Threads 2 and 3 are the relevant ones for our purposes.

It spends a lot of time in `libffi` and ctypes, we can probably avoid this by removing the indirection or using a better system for generating FFI bindings.

It also spends a lot of time in `malloc_consolidate` which is part of the `malloc` infrastructure. This is because `libff::bigint::randomize` is very inefficient. It opens an fd for `/dev/urandom`, reads the requisite number of bytes using `fread` and then closes the fd. Every time you call the function. `fread` does buffering and allocates the buffer with `malloc`. Speculating, that generates a lot of tiny heap objects when have to be consolidated later. It should be opening `/dev/urandom` *once*, then the buffering will be an optimization instead of pessimization.

Looking at the actual arithmetic, there might be more low hanging fruit there, though I'm less confident. Spending so much time in `libff::mnt6_G1::is_zero` is suspicious. Looking at the [source code](https://github.com/o1-labs/snarky/blob/9374fe4454a2dee6520b1014273b7b2482956c87/src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/fields/bigint.tcc#L89) it's checking whether the value is zero byte-by-byte. We should be able to do it one 64 bit word at a time, at least, and maybe use vector instructions to go even wider. It also spends a bunch of time in `mul_reduce` but that looks like they micro-optimized it so I don't know how much we'll be able to squeeze it.

**Comment by mrmr1993** [comment]
> It spends a lot of time in `libffi `and ctypes, we can probably avoid this by removing the indirection or using a better system for generating FFI bindings.

I've been thinking of doing this for a while; will bump it up my priorities list and have a crack at it tomorrow.

> It also spends a lot of time in `malloc_consolidate`

Also speculating, but I think a big part of that may be that **all of the libsnark allocations in snarky** go through C++'s `new` and `delete`. I can't see load the profile on my phone to make a judgement call, but if it seems worth it, I'm happy to rewrite the libsnark bindings to use the OCaml heap.

> Spending so much time in `libff::mnt6_G1::is_zero` is suspicious.

I'm cautiously optimistic that compiling libsnark with the `PERFORMANCE` flag enabled will help with this. It's not turned on because it greatly increases compile times, but for the testnet release we definitely should have it on, and we should probably get some profiling info based on it before then.

**Comment by mrmr1993** [comment]
We're no longer using `libff`, and the equivalent to the proposed changes has been done for the rust backend. Closing.
