### ISSUE TITLE
"block recieved too late" happens on honest network

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#2954]
log message:

Warn: Not rebroadcasting block $state_hash because it was received "6 slots too late"

happens on a fully honest network. May indicate a bug in when blocks are rebroadcasted and received, as mentioned in comments below

**Comment by cmr** [comment]
I think catchup will broadcast old blocks right now...

**Comment by enolan** [comment]
We also have a bug where blocks are (or appear to be) late by exactly delta
slots for some reason. And I mean they arrive 2*delta slots after their
actual slot, they're not considered late if they're <= delta slots after
their slot.

**Comment by nholland94** [comment]
This message is fine. It merely indicates that the system chose to not rebroadcast some blocks that were acquired during ledger catchup, which is what we want it to do. I think the fix here is to make this log message a lower level, such as debug.

**Comment by nholland94** [comment]
https://github.com/CodaProtocol/coda/blob/master/src/lib/coda_lib/coda_lib.ml#L477

code for reference

**Comment by es92** [comment]
I’m cool with the message and log level, more referring to why it’s being triggered as a bug (sounds like something in catchup, plus blocks arriving late by some multiple of delta?). Will edit body to make clear referring to that

**Comment by nholland94** [comment]
What I meant before is that this is actually not a bug an is expected behavior. That is why I recommended downgrading the log message. This is the intended behavior which is triggering at the intended location. However, we could try and update the code to have more granularity for this log. For instance, this point in the code cannot differentiate between the source of transitions, which could be useful for identifying issues with the transition frontier controller in the future.
