### ISSUE TITLE
CRASH - proposer - Generated transition $state_hash was never accepted into transition frontier

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#3155]
Happened during testnet breakdown on 2019-08-08

```
    (monitor.ml.Error
  "Generated transition $state_hash was never accepted into transition frontier"
  ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
    "Called from file \"lib/proposer/proposer.ml\", line 442, characters 26-59"
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))
```

Full logs:
https://s3-us-west-2.amazonaws.com/crashlogs.o1test.net/testnet_share_the_wealth/2019-08-08/crashlog-proposer-state_hash-was-never-accepted.tar.bz2

**Comment by ghost-not-in-the-shell** [comment]
I scanned through the logs. There're a lot of long async cycles. You can see 1 every 10-20 lines of log. One of those took 11s and another took 15s. And the timeout for proposed transition to get into frontier is 15s, so it timed out.

As to why there're so many long async cycles, I have no idea ...

**Comment by nholland94** [comment]
I believe https://github.com/CodaProtocol/coda/issues/3155 is the root cause of this issue. Proposer proving process was competing with snark worker proving processes for CPU time, causing the proposer to take too long to produce a proof. Not closing this until we add a fix to gracefully handle this edge case in the proposer code and confirm that this is not happening anymore. Removing this from the prioritization board in favor of the other issue for now.

**Comment by ghost-not-in-the-shell** [comment]
It seems like after turning off the snark worker, we still have long async cycles...

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
