### ISSUE TITLE
`Bootstrappable_best_tip` should not require the consensus state of the node's best seen consensus state

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#3174]
Reference to this PR comment https://github.com/CodaProtocol/coda/pull/3112#discussion_r311316319

We automatically filter out transitions that causes us not to bootstrap in the verification process. The prover doesn't have to do that.

**Comment by imeckler** [comment]
Some node is trying to do bootstrap, gives its peers its consensus state S. 

Peers respond back by giving their best tip X only if the X is bootstrappable from S.

Basically `None` is not a valid response to the bootstrappable-tip RPC. 

This doesn't really change anything since adversaries can still respond with whatever, it's just a code hygiene thing.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
