### ISSUE TITLE
Specify Bootstrap Peer (fork recovery technique)

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#3179]
Discovery currently provides all peers. (good and bad potentially)

When a network is forked it is valuable to be able to specify a known-good peer who you wish to bootstrap from. (to avoid re-syncing with a bad fork)

**Comment by jkrauska** [comment]
could be collapsed in to an extension flag.

-peer a.b.c.d:8303 -bootstrap-from-peer

**Comment by nholland94** [comment]
I see no reason why we can't add this, though I believe we should discourage users from using this and primarily only use this internally. Our bootstrap logic right now is simple and needs some improvements in order to help avoid syncing to bad forks. Furthermore, there shouldn't even be bad forks. We should focus our engineering effort (heavily + soon, imo) on making our nodes more resilient when bootstrapping and catching up rather than relying on a tool that we should discourage the use of during mainnet. Though, as I said at the beginning, we should at minimum add this for internal usage when we do experience forks on our networks and want to recover our nodes onto the correct fork.

**Comment by imeckler** [comment]
The intent here is to do manual recovery from forks on testnets. We shouldn't require this in normal operation.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
