### ISSUE TITLE
Look at staged ledger errors and decide whether or not to crash

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#3366]
Some of them would indicate bugs, other are recoverable

**Comment by imeckler** [comment]
See https://github.com/CodaProtocol/coda/issues/3350

**Comment by deepthiskumar** [comment]
All the staged ledger diff errors when proposing a block indicate bugs (the block is discarded when applying someone else's block)
1. `Invalid_proof`: Proofs purchased don't verify. Should not happen since we are now verifying proofs before adding it to the snark pool
2. `Insufficient_work`: Not enough work purchased (either not available or not included because of some bug in `create_diff`)
3. `Bad_signature`: This is not currently in the code flow when proposing a block because of always using transactions of type `With_valid_signature.t`. But if that changed and if it were to fail with this error then the diff created has invalid transactions and therefore should be dropped.
4. `Coinbase_error`: When coinbase is split incorrectly 
5. `Coinbase_error`: When the snark fee is greater than coinbase amount. #3672
6. `Insufficient_fee`: When transaction fee is not sufficient to pay for the snarks
7. `Non_zero_fee_excess`: When the diff created does not account for all the transaction fees. 
8. `Unexpected_error`

For all the above errors except `Unexpected_error` (for which we crash) , we currently discard the block created and continue proposing. All these errors indicate a bug in the `create_diff`function. There are unit tests for all except `Invalid_proof`, `Bad_signature`, `Coinbase_error` (when the fee is too big). So we probably don't have to crash the daemon for these errors but have a fatal log message or a metric to indicate their occurrence when running the testnet.
