### ISSUE TITLE
Have the archive node build check pass circleci

### ISSUE THREAD

**Issue by wu-s-john** [MinaProtocol/mina#3559]
I made a check on circleci that validates that uses a Hasura docker container to produce an introspection_query json file and validates if it matches the existing used in the archive app and then it compiles the archive app code. 

However, getting this check to pass circleci is much harder than I anticipated. I made the check in this [PR](https://github.com/CodaProtocol/coda/pull/3447).  It seems like the "simple" circleci solutions cannot easily support the new infrastructure introduced by the archive node.

Namely, the problem got introduced was that the Hasura docker image needs to depend on the existence of the Postgres docker image. You cannot easily make the Hasura docker image start after the Postgres docker image has been started in Circleci when your execution context is a docker type. Most of the tests and compile checks are done on the Coda docker. However, we may need to run these checks in a Linux machine to support this dependency.

**Comment by bkase** [comment]
Why do we have to use hasura and Postgres from separate docker containers, can we just direct install them as ci steps? In prod these will be deployed as managed aws services afaik?

**Comment by yourbuddyconner** [comment]
> Do we have to use hasura and Postgres from separate docker containers, can we just direct install them as ci steps? 

Please no, he's doing it right. I will take a look.

**Comment by yourbuddyconner** [comment]
So to reiterate the problem here, this test has a dependency chain of docker conatiners that need to be started in-order -- this is primarily due to the Hasura container throwing errors and dying when postgres is not running during its startup process. 

This can be easily remedied with one of several common scripts ([wait-for-it.sh](https://github.com/vishnubob/wait-for-it), [dockerize](https://github.com/jwilder/dockerize), etc.) which can be used to wait for a TCP socket to be opened before executing the main container process. 

You can see an example of the wait-for-it.sh usage in the bot here: https://github.com/CodaProtocol/coda/blob/develop/frontend/bot/Dockerfile#L20-L21
