### ISSUE TITLE
Crash report - 2019-10-17

### ISSUE THREAD

**Issue by Cris-F** [MinaProtocol/mina#3699]
Crash report - 2019-10-17
-------
Hi,

- Daemon crashed and asked that I report here.
- I set up the node and synced.  
- Then requested funding from the faucet.  
- Received txid.
- Waited ~5 blocks but no funds shown received with **coda client get-balance -address $CODA_PK**
- Went to sleep.
- Daemon crashed sometime during the next ~5 hours.

I can be contacted on Discord if you need anything else.

CrisF#3405

Crash Report attached
[coda_crash_report_2019-10-17_17-49-32.606241.tar.gz](https://github.com/CodaProtocol/coda/files/3743635/coda_crash_report_2019-10-17_17-49-32.606241.tar.gz)

**Comment by cmr** [comment]
Hi @Cris-F. This crash looks like it was due to some network error: when the Kademlia helper was restarted, it failed to connect to any of its peers, leading to this crash. Either the local network connection went down, or all of your peers simultaneously died. 

We shouldn't crash in this situation: we should wait and listen for incoming connections and retry old connections once the network is back. This should be better with the next testnet release and the new libp2p-based discovery code.
