### ISSUE TITLE
RPC handshakes failing - snark work not being transmitted

### ISSUE THREAD

**Issue by jkrauska** [MinaProtocol/mina#3833]
snark work done on a coordinator does not appear to be successfully transmitted to other peers.

seed node sees 378 jobs to be done
```
admin@over-9000_us-west-2_seed_0:~$ coda advanced pending-snark-work | jq '. | length'
378
```

snark-coordinator sees 366 jobs to be done
```
admin@over-9000_us-west-2_snarkcoordinator_0:~$ coda advanced pending-snark-work | jq '. | length'
366
```

lots of these types of errors in log:
[coda.log.backup.gz](https://github.com/CodaProtocol/coda/files/3805494/coda.log.backup.gz)

Handshake_error.Handshake_error

Possible connected to other errors?

**Comment by jkrauska** [comment]
Q: Do we try to retransmit completed snark work later if it fails on initial send?

**Comment by jkrauska** [comment]
This is happening hundreds of times in 10m periods.

```
admin@over-9000_us-west-2_snarkcoordinator_0:~/test-coda$ grep Handshake coda.log | grep "2019-11-04 18:2" | wc -l
352
admin@over-9000_us-west-2_snarkcoordinator_0:~/test-coda$ grep Handshake coda.log | grep "2019-11-04 18:3" | wc -l
414
```

**Comment by jkrauska** [comment]
Happening across all peers

```
admin@over-9000_us-west-2_snarkcoordinator_0:~/test-coda$ grep Handshake coda.log | grep host | jq .metadata.peer.host | sort | uniq -c
     64 "18.144.65.105"
     65 "34.209.213.124"
     62 "34.211.204.59"
     59 "34.223.0.200"
     60 "3.84.187.208"
     61 "52.39.168.248"
     61 "52.89.119.99"
     58 "54.184.247.241"
     63 "54.193.66.7"
```

**Comment by jkrauska** [comment]
Sending and receiving nodes are not banned.

**Comment by jkrauska** [comment]
Seemingly related to 
Gossip net TCP server cannot open another connection.

**Comment by jkrauska** [comment]
Disabled TCP server limits with "-limit-concurrent-connections false"

Still observed inability of snark-coordinator to transmit completed snark work.

**Comment by ghost-not-in-the-shell** [comment]
In current implementation, we would broadcast a new `snark_pool_diff` every time we receive a snark work from snark worker. This is a problem for snark coordinator because snark coordinator has multiple snark worker. Snark coordinator would receive a lot of snark worker in a short period of time. Therefore snark coordinator would broadcast `snark_pool_diff` very frequently and lead to the concurrent-rpc-connection problem.

In the new libp2p implementation, gossip would no longer use rpc call, so this would go away. A short term fix could be the following:
Creating a buffer to store completed snark work, and broadcast periodically from the buffer by packing up multiple snark work into a big snark_pool_diff.
