### ISSUE TITLE
Sentry node related libp2p changes -- Ember

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#4369]

**Comment by aneesharaines** [comment]
Need to add notes and choices to a small RFC

**Comment by emberian** [comment]
Instead of an RFC document, I thought I'd just leave a comment here for discussion. Happy to move into an md file if we want.

The idea here is to protect block producers from DoS by forwarding their local broadcasts to a set of publicly known "sentry" nodes and otherwise disconnecting them from p2p communications. This will require two independent bits of daemon work:

1. Hidden mode. Daemons in hidden mode will not initialize kademlia or use any discovery/pubsub functionality. This should probably be a new boolean configuration to `Gossip_net` and the helper, to disable these resources. When in hidden mode, instead of broadcasting using pubsub, do a new RPC (`Sentry_forward`?) to a configured list of "sentry nodes". These will need to be full IP/port/peer ID pairs, since discovery won't be able to find any of that information. Connections from all other IPs will be denied.
2. Sentry mode. Daemons in sentry mode will accept `Sentry_forward` RPCs from configured peers and otherwise deliver an instaban. They are otherwise full, regular participants in discovery/gossip. These daemons will forward all valid broadcasts (blocks/snark work/txns) they receive on to their hidden nodes.

New hidden mode args:

- `--hidden-mode` to disable discovery/pubsub.
- `--trust-sentry MULTIADDR` to add to the `Sentry_forward` trust list

New sentry node args:

- `--sentry-for MULTIADDR` to add a hidden daemon for forwarding.

The sentry trust list should have GraphQL endpoints for inspection/manipulation, and accept configuration from the JSON config and not just the CLI flags.

This should be enough to implement network topologies [like the Cosmos sentry node architecture](https://forum.cosmos.network/t/sentry-node-architecture-overview/454).

I think we can still use libp2p for sentry<->hidden communications, modulo this open question: will connections from the hidden node cause the sentry nodes to broadcast the hidden node as a potential peer? Ideally hidden nodes wouldn't be publicly routable, but if they are this would leak the IP.

**Comment by emberian** [comment]
Idea from Luke: allow RFC1918 connections in addition to manually configuring IPs, makes cloud provisioning easier.

**Comment by emberian** [comment]
We could possibly use this instead of manually forwarding at the coda rpc level?

https://godoc.org/github.com/libp2p/go-libp2p-pubsub#WithDirectPeers
