### ISSUE TITLE
[Bug] Memory Leak in Daemon

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#4442]
Been keeping an eye on memory consumption in my current QA Network and it looks like there might be a small leak somewhere. Over the weekend average memory consumption increased by ~600mb for a rate of ~200mb/day of operation. 

<img width="1662" alt="Screen Shot 2020-02-24 at 10 13 07 AM" src="https://user-images.githubusercontent.com/2635475/75179139-4bac2700-56ee-11ea-91f3-2051659e47e7.png">

Block Producer Dashboard scoped to the time range: https://o1testnet.grafana.net/d/Rgo87HhWz/block-producer-dashboard?orgId=1&var-testnet=regeneration&var-role=block-producer&from=1582344862277&to=1582567501200

@nholland94 might have some hypothesis about the culprit

**Comment by aneesharaines** [comment]
@emberian to investigate the scale of the issue.   Also we could run the memory profiler tool, Valgrind or spaceTime to help investigate.

**Comment by emberian** [comment]
Graph from the latest net (gerald): https://o1testnet.grafana.net/d/Rgo87HhWz/block-producer-dashboard?var-testnet=gerald&var-role=block-producer&from=1582156800000&to=1582934399000

It's still exhibiting what potentially is memory leak behavior when there's blocks happening, but it seems to be about 1GB/day which isn't the worst (means we need to restart every few days for modest resources?). The latest run of Gerald seems to exhibit different/worse memory behavior, possibly due to some additional debugging?

**Comment by emberian** [comment]
![memory use graph](https://user-images.githubusercontent.com/704250/89088768-d9033f80-d34e-11ea-987a-03f4b13f937f.png)

Looking pretty good right now.
