### ISSUE TITLE
Website: Multiple languages

### ISSUE THREAD

**Issue by LukasGerm** [MinaProtocol/mina#4471]
Hello guys,

I am translating the docs to german and I would like to have the opportunity to make a pull request on the translations. At the moment we do not have the option of having multiple languages.

It would be nice of someone could add support for multiple languages so that we can get our work online. I would do that but I have no experience in ReasonML and no time to learn it.

**Comment by Schmavery** [comment]
This is a change with potential implications of how the site/docs work, so it would be great for us to discuss tradeoffs of different approaches before making a full PR if this is a feature we determine would be desirable for the main site.

My understanding up until this point was that most translators wanted to host their own translations in order to get the traffic coming to their own site etc. (cc @kbase)

We then have to make the decision about whether the whole site needs to support internationalization or if it's useful to just translate the docs. Assuming we just want the docs, I can imagine some potential approaches:

- The simplest implementation of this I can see would be to copy the ./pages/docs folder to have `./pages/docs/fr`, `./pages/docs/de` etc, with a copy of the docs in each, translated to the appropriate language. Obvious downsides of this include it becoming very difficult to keep the docs in sync, as well as all links to the docs from other pages needing to default to a specific language, which could be a pain for non-english users. This also ignores the issue of handling the docs side nav component, which would not be internationalized in this case.
- Another option would be some sort of integration of react-intl with nextjs/mdx. There are some existing attempts in the open-source world to create libraries for this, but I'm not sure if any of them support the NextJS features we use (I haven't looked recently). This could make it slightly easier to restructure the docs pages and may make it easier to create an internationalized docs side nav component.  Likely only a small part of this will be writing reason code, mostly it will be figuring out how to make the next+mdx structure handle the kind of internationalization support we need.
- ??? Feel free to suggest any other ideas

General considerations for this feature:
- How can we make sure docs pages between languages keep the important stuff in sync and don't diverge over time
- How can we avoid making it too difficult to update/improve the docs. The obvious risk is that any change to the docs will need to be translated before being published. This could get more complicated if we end up needing to add versioning to the docs.
- Is it too high of a barrier to expect external translators to make PRs to our monorepo in order to contribute? In the past, we've wondered if this was the case.
- No matter which implementation we go with, there will be implications for the design of the docs pages, since we will need to have some sort of language switcher somewhere on the page.

edit: just saw that https://github.com/CodaProtocol/coda/pull/4489 was opened, which is cool, thanks for contributing to the development of the site! I think it might still be worth thinking about design tradeoffs for a feature like this.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
