### ISSUE TITLE
Disaster recovery / hard fork data requirements

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#4858]
[From discussion of May 7, 2020]

What data do we need to save / restore when there's a disaster?

For purposes of this issue, a disaster is when the network no longer functions, because, say, many nodes are crashing, or the network is badly forked

Related issues:
 - which block to start from, and from which machine
	- picking a block from an O(1) machine violates the spirit of decentralization
    - most recently finalized block?
    - last block in strongest chain?
    - do we need to change the genesis timestamp, or have another timestamp at the point of recovery?
    - can constants change (chain strength) at the point of recovery?

Required data:
 - root block to start from
 - root SNARK 
 - SNARKed ledger
 - root history (window of 2*k blocks preceding root)
 - 2 epoch ledgers

Optional data, not for MVP:
 - transactions in best tip blocks beyond root
 - SNARK pool
 - Note: these would allow trying to get those pending transactions into the consensus

If restoration from saved state fails, we could use a strategy of replaying blocks from an archive node. That's computationally expensive, and a last resort.
We'd need a bespoke tool for this purpose.

Related PRs:

 - #4115 

Related issues:

 - #4859

**Comment by psteckler** [comment]
The saved state consists of several pieces. Do we need to make sure they're synched with one another? Do we need a `recovery-state` type to account for these pieces?

**Comment by psteckler** [comment]
Can we sketch the algorithm to load the recovery components? 

For example, we have components related to the root. What data structures in the existing implementation would be instantiated from those components?

**Comment by psteckler** [comment]
The needed state should be dumped using a CLI client command.

Design goal: the daemon should load after a hard fork just as it does normally. 

Either the CLI command will create the needed genesis information, or the command can dump just the raw state, and a tool will transform that data into genesis information.

**Comment by deepthiskumar** [comment]
The epoch ledgers that we store are valid for the best tip. The root could be in the previous epoch and therefore the current epoch ledgers will not be valid anymore. @ghost-not-in-the-shell is working on epoch ledger where checkpoints are added to the snarked ledger for the two epoch ledgers `staking_epoch_snapshot` and `next_epoch_snapshot`. We will need to add another checkpoint `previous_epoch_snapshot` which is the `staking_epoch_snapshot` for the previous epoch (the epoch root could be in)
When we save the data for hard fork/disaster recovery, if the root is in a different epoch that the best tip then, the two epoch ledgers that we need would be `previous_epoch_snapshot` and `staking_epoch_snapshot` that will change to `staking_epoch_snapshot` and `next_epoch_snapshot` respectively, when we restart the network. Otherwise, we use the `staking_epoch_snapshot` and `next_epoch_snapshot` as is.

**Comment by deepthiskumar** [comment]
Regarding proofs, we need to be able to verify the proof of the block that we start from. If the keys don't change then it is straightforward. We might need two copies of the constants since genesis timestamp might have to be reset otherwise there would be quite a few empty slots.
If they keys change, then we need a mechanism (store all the required keys?) to verify older proofs (both blockchain and transaction snarks). There is a section in https://github.com/CodaProtocol/coda/pull/3990 about transitioning parallel scan, could be a possible solution.

**Comment by aneesharaines** [comment]
There may be outstanding questions that come out when the RFC is started...

**Comment by aneesharaines** [comment]
Blockchain transition RFC is out for review with discussion on the best approach to take.  @psteckler  is going to summarize and have a discussion about the proposed approach
