### ISSUE TITLE
[RFC] Issue Ingest Process

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#5124]
Community feedback is invaluable in improving our protocol, however it's important that the vast majority of issues that are in our backlog are actionable. 

In the interest in improving "Issue Quality", O(1) should implement a process to prune and triage issues as they come in. Initially, this should target Feature Requests and Bug Reports, but there is improvement that could be made in our backlog of core issues as well. 

## Issue States: 

**Untriaged:** 
- Issue has not been triaged by a Core Team member 

**Needs More Info:** 
- Issue needs more information from the reporter or some other followup information to be actionable. 
- Issues in this state are auto-closed after 14 days. 
- Issues that do not fill out the issue templates properly (ex. replace the default issue title) automatically enter this state. 

**Actionable:** 
- Issue is actionable and has been placed in a project backlog
- Issues assigned to a project are immune to auto-closure 

## Implementation: 

**Daily:**
- Testnet Guardian triages issues
  - Request more Info
  - Merge Related Issues ("Closing in favor of #????")
- Issue Bot auto-closes issues that have been in the `Needs More Info` state for more than 14 days. 
- Issue Bot automatically requests more information where possible. 

**Weekly:**
- Testnet Guardian reports on outstanding bugs and feature requests

**Comment by nholland94** [comment]
I like this, and think it's something we desperately need. I have some notes on some of the details around the "needs more info" status, though.

> ### Needs More Info:
> - ...
> - Issues that do not fill out the issue templates properly (ex. replace the default issue title) automatically enter this state.

I think this is an interesting idea to enforce compliance, though we need to decide what scope our template should exist within. We sort of have 2 kinds of issues on github: bugs and work items. The templates around these two kinds of issues likely make sense to be different. For instance, we want to ensure that uses submitting bugs upload crash reports and write down information about the behavior that exhibited the bug. Those sections are not really applicable to work items, which instead need to have sections for what the work is, why it should be done, and an optional section with some thoughts about how it can be done.

> ### Needs More Info:
> - ...
> - Issues in this state are auto-closed after 14 days.

I think whether or not we should do this depends on whether or not the issue will auto-migrate to the "actionable" state when a user updates an issue (more on this in a sec). The reason I say this is because, if the migration between "needs more info" and "actionable" is a manual process that has to be done as part of issue triage (where a triage participant would regularly go through the "needs more info" issues and see if the info has been attached), then I think that we should err towards not auto-closing issues if they are in this state for more than 14 days. What would make sense is to label an issue as "stale" after 14 days, and have triage reviewers go through "stale" issues regularly, closing them if they deserve it. This would provide one last (easy) layer of manual review to ensure that we don't accidentally close user issues that were important for one reason or another, or so that we don't accidentally let our bot close issues that just didn't have its status properly updated by us in time.

RE: whether or not we should auto-migrate "actionable" issues. The answer to that is probably no, since just the mere fact that a user updated an issue does not make it "actionable" -- they would just be bumping it or providing partial answers. That said, the rule could be "close issues after 14 days of no informative activity", but that is beside the point. This would all seem to indicate the answer to "should be auto-close issues" would be no as well, if you believe my above paragraph.

Something else we should begin to approach as a topic is how we plan on dealing with triaging our existing issues. This plan will help tremendously with new issues coming in from testnet users, but we will also need to do a big historical cleanup on issues soon. This may not be the place to fully flesh that decision out, but I wanted to mention it here as it makes sense to fix our issues all at once (and sooner rather than later).

**Comment by yourbuddyconner** [comment]
@nholland94 yes, I agree with your sentiments and under this current basic design the Testnet Guardian would receive the full burden of having to go through the recently updated `needs-more-info` issues. 

Though, simply updating an issue would reset this timer, and if it's been more than 14 days since that issue was updated, under the assumption that the queue is looked at daily, that issue has 14 chances to be moved out of the "danger zone."

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
