### ISSUE TITLE
Measure/test current VRF time

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5172]
Benchmark framework where this is already measured?  @psteckler to check!

**Comment by psteckler** [comment]
On my desktop:

```
┌──────────────────────────────────────────────────────────────────────────┬──────────┬────────────┬────────────┬────────────┬────────────┐
│ Name                                                                     │ Time/Run │    mWd/Run │   mjWd/Run │   Prom/Run │ Percentage │
├──────────────────────────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼────────────┼────────────┤
│ [src/lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval unchecked │   1.01ms │    19.78kw │    15.22kw │    15.22kw │      1.67% │
│ [src/lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval checked   │  60.38ms │ 4_680.42kw │ 1_513.58kw │ 1_512.39kw │    100.00% │
└──────────────────────────────────────────────────────────────────────────┴──────────┴────────────┴────────────┴────────────┴────────────┘
```

**Comment by psteckler** [comment]
With `testnet_postake_medium_curves`:
```
┌──────────────────────────────────────────────────────────────────────────┬──────────┬────────────┬────────────┬────────────┬────────────┐
│ Name                                                                     │ Time/Run │    mWd/Run │   mjWd/Run │   Prom/Run │ Percentage │
├──────────────────────────────────────────────────────────────────────────┼──────────┼────────────┼────────────┼────────────┼────────────┤
│ [src/lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval unchecked │   4.70ms │    19.73kw │    15.40kw │    15.40kw │      2.69% │
│ [src/lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval checked   │ 174.75ms │ 9_277.51kw │ 2_792.95kw │ 2_789.93kw │    100.00% │
└──────────────────────────────────────────────────────────────────────────┴──────────┴────────────┴────────────┴────────────┴────────────┘
```

**Comment by psteckler** [comment]
I created a benchmark for the unchecked eval (`T.eval`) in `Proof_of_stake`. adding `truncate` and `is_satisfied` steps. With medium curves, those additional steps added about 0.05 msec.

**Comment by bkase** [comment]
So ~5ms for a vrf check that may miss

We cycle through each delegator per slot. This means even 1000 delegators can go through a slot every 5s. We also short-circuit whenever a slot wins, so this means with 1000 delegators, you can still go through ~10 slots before missing a slot. And if you expect to win once a day, it will take 40min with 1000 delegators (missing ~12 slots), 4min with 100 delegators (missing ~1 slot)

**Comment by bkase** [comment]
There was a flaw in my reasoning. Reality is better than I described above:

Since 1000 delegators can go through a slot every 5s and since we short-circuit when a slot wins, either we'll know we've won the first slot within 5s or we'll know we didn't and can move on. If we didn't win the slot, it doesn't matter that we're still checking VRFs.

Let's assume we could support 10,000 delegators (I imagine some component would fail as we haven't tested this yet), but that would take ~50s and this may be pushing it if we push snark times down successfully. Unfortunately, this would "loop" in the sense that this would happen every slot.

And it's a potential vector for a denial of service attack on a block producer. We could hack in some form of mitigation where you could take only the top X folks delegating to you sorted by stake.

So the question is: Is this an acceptable world? Where an operator can only take into consideration the top thousands of accounts' delegations? To support more an operator would need to spin up another block producer with a separate keypair.

tl;dr
100 delegators = 0 missed slots
1000 delegators = 0 missed slots
10,000 delegators = a problem, and a vulnerability that we could patch

(would still love someone double-checking my reasoning though)

**Comment by aneesharaines** [comment]
@imeckler  to run these on the new snark branch also

**Comment by imeckler** [comment]
For the new SNARK
```
Estimated testing time 20s (2 benchmarks x 10s). Change using '-quota'.
┌──────────────────────────────────────────────────────────────────────────┬─────────────┬─────────────┬──────────┬──────────┬────────────┐
│ Name                                                                     │    Time/Run │     mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├──────────────────────────────────────────────────────────────────────────┼─────────────┼─────────────┼──────────┼──────────┼────────────┤
│ [src/lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval unchecked │    278.41us │      6.63kw │   4.95kw │   4.95kw │      0.40% │
│ [src/lib/vrf_lib/integrated_test.ml:vrf bench module] vrf eval checked   │ 70_347.06us │ 30_353.73kw │ 553.27kw │ 553.27kw │    100.00% │
└──────────────────────────────────────────────────────────────────────────┴─────────────┴─────────────┴──────────┴──────────┴────────────┘
```

**Comment by aneesharaines** [comment]
So we need to figure out where the network breaks with different number of delegators.  This is a great use case for the work to spin up multiple QA nets with different configurations.    @yourbuddyconner FYI we can make this our first use case?
