### ISSUE TITLE
Runtime Fork - Immediate Fork at Height = 4 

### ISSUE THREAD

**Issue by yourbuddyconner** [MinaProtocol/mina#5365]

**Comment by emberian** [comment]
One thing we're seeing is this:

> "From the current prover state, got None for the expected next state, which should be true only when calculating precomputed values"

This is pretty bad? For some reason computing the expected next state failed? The only time that should ever be None is when computing a genesis block I think. About 73 in 1.5 hours on one run. It does look like nodes are crashing and restarting before producing that message. Shouldn't the prover state be present after that though, since it's loading the genesis state from parameters? Is this a benign artifact of that?

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
