### ISSUE TITLE
Upgrade OCaml to 4.10 or 4.11 ?

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5413]
We should scope this out so that we can make an informed trade off here.  

Current thinking is there may be useful features in 4.11, which is in beta.  We should wait until its released and the needed libs are supported. 

Revisit after taskforce to add to roadmap

**Comment by mrmr1993** [comment]
These are mainly ppx things that are fixable with the new APIs. This needs work from @psteckler and I, but individual tasks are small, can be done over time.

There are potentially big simplifications that we could make now that modular explicits are on the roadmap ([relevant PR](https://github.com/ocaml/ocaml/pull/9187) (intent to ship, but this is mine and O(1) isn't currently supporting me in pushing this through), but beyond that we only benefit from performance gains.

There is intent to ship multiprocess stuff that would give us huge improvements.

We should do this, but priority should be balanced, since most large improvements that we would benefit from are pending.

**Comment by psteckler** [comment]
See also the problems I encountered when I looked at 4.08: #2743.

**Comment by psteckler** [comment]
We've settled on 4.11.2.
