### ISSUE TITLE
Testing 100k accounts with bootstrap failure mode (testing mask chaining)

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5590]
Run a network w/ 100k accounts,
Submit as many transactions that modify accounts as possible - need to update test txns to modify accounts as part of running the testnet
Then kill a node and monitor it as it comes back up

**Comment by aneesharaines** [comment]
Run a network w/ 100k accounts,
Submit as many transactions that modify accounts as possible - need to update test txns to modify accounts as part of running the testnet
Then kill a node and monitor it as it comes back up

**Comment by aneesharaines** [comment]
Snarks turned off

**Comment by mrmr1993** [comment]
* Found a stack overflow while generating 100K ledgers: #6250
* Made batch-applying large updates to the ledger > 10x faster on 100K ledgers: #6251 
  - 10x is a very conservative estimate, likely to be 500x or more; no actual data because I never saw the original function complete.
* Used batch apply for ledger transfers: #6255
  - This avoids 400,000 unnecessary database queries when initialising a 100K ledger

**Comment by mrmr1993** [comment]
Seeing a crash on bootstrap, but didn't manage to attach to the bootstrapping process to debug it before the crash, and logs showed nothing useful.

Working on a fast way to reproduce a known peer state to make iteration time shorter, which should also have more general use. First PR in the series is #6327, more to follow.

**Comment by mrmr1993** [comment]
Been testing with ~1500 blocks with ~10000 transactions, I'm seeing a large memory leak that ends up exhausting my RAM. Currently investigating, will set up a spacetime run overnight to try and get more data if I don't find it before then.

**Comment by mrmr1993** [comment]
The spacetime profile seems to indicate that we're holding multiple copies of accounts, merkle paths, transactions, blocks, etc. which is causing the high memory usage. For example, every time we read an account from the rocks db, we deserialise a new distinct copy of the account.

Some extra testing shows memory increasing at an increasing rate over time, and extra data on the number of allocated field elements shows similar behaviour. The data from one run is here (Excel document, sorry): [100k_accounts_memory_data.xlsx](https://github.com/MinaProtocol/mina/files/5390004/100k_accounts_memory_data.xlsx).

Some graphs generated from the data:
![Field_elements_vs_memory](https://user-images.githubusercontent.com/1847343/96227775-8409b980-0f8c-11eb-9928-8a7b915e0a68.png)
![New_field_elements](https://user-images.githubusercontent.com/1847343/96227803-8cfa8b00-0f8c-11eb-8294-7d27b04a7542.png)
![Memory_per_field_element](https://user-images.githubusercontent.com/1847343/96227814-908e1200-0f8c-11eb-80f1-4ed2a2524781.png)

Holding more data on-disk instead of in memory would obviously help, but it's not clear to me how much work it would be to do so.

**Comment by mrmr1993** [comment]
Collected some stats on ledger masks. Garbage collecting before and after `Full_frontier.move_root` shows memory usage change by ±100KB. Even if the worst case of a 100KB increase happens each time, we would only see 150MB across the 1500 block trials, so we can probably rule it out.

**Comment by mrmr1993** [comment]
Valgrind is inconclusive, seems to be incompatible with `Async`s pipes and crashes immediately across several runs.

Currently investigating the best way to implement an OCaml heap explorer. Once we have this, dumping the memory of the process should conclusively show where the memory is being held.

**Comment by mrmr1993** [comment]
High memory usage is from bad interaction between the OCaml GC and rust heap. Enough values live long enough to make it into the OCaml major heap, and they're small (1 word each), so they hang around there. This leads to lots of fragments in the rust heap where memory that should have been freed is scattered around, but OCaml doesn't feel the heap pressure or need to free them because its own heap is small.

Solution is to rewrite the rust bindings to use the OCaml heap. I'll start on this after I fix the latest QA-net bug.
