### ISSUE TITLE
Determining h

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5851]
Determine how we and other block producers would determine h.   

If easy, we can then turn this into a tool

**Comment by deepthiskumar** [comment]
1. For a planned hard fork, we can choose a slot to fork off of and wait till k blocks  for it to be finalized. The k blocks generated during the wait time will be discarded and so will any transaction included in them. They are only to ensure any short forks at the given slot are resolved.
We can then ask block producers/validators to send us the ledger state at that slot. There should only be one block at that slot because it would have been finalized.  The state would include the protocol state hash and the ledger in the runtime-config json format. We could have a cli command to generate this state since this is a planned fork and daemons are expected to be running. We wouldn't have to replay blocks from the archive DB in that case

2. For an unplanned hard fork: 
  a) If the nodes are still up and the block (for a given slot) we want to pick is within the last `2*k` to `k` blocks then we could use the same cli command to get the ledger as described for planned hard forks
 b) If the nodes are crashing or that the block we want is older than last `2*k` blocks , then we have to rely on logs to identify the block we want the state from and run the replayer to obtain the ledger corresponding to that state.
When qa-ing, I've been looking at this Best tip diff log `added %d breadcrumbs and removed %d making path to new best tip` to identify the best tip. (haven't yet added structured logging to it)
   From this log we can also extract the chain to the root or any block beyond the root. Alternatively we can use the archive database to extract a state hash along the chain given the best tip hash.

Open questions: 
1. There was no consensus ( not that I know of ) on how many blocks we can go back to fork off of. It is safe to take any block beyond the first `k` blocks because they would have reached finality. However, this would mean we discard all the transactions included in recent `k` blocks. Choosing a more recent block would mean we risk leaving out a better short fork
2. Can we expect block producers to persist logs for sometime (an epoch should be plenty i think) so that we can extract the latest best tip from those logs and use the state that's on majority of the nodes. This is during the disaster-recovery mode where the nodes are not running

**Comment by aneesharaines** [comment]
@deepthiskumar I think we need be able to select a block earlier than k blocks:  
https://docs.google.com/document/d/1AHbUA9WQUQhI1DaU40BRfU561vdVbEuVBVQ1fR7vH_w/edit

Also adding @bijanshahrokhi and @vanishreerao for their thoughts.

**Comment by deepthiskumar** [comment]
Selecting a block earlier than k is safe in terms of omitting a possible valid fork since all the blocks older than k are finalized. I think the only time we'd want to select some block older than k is when the blocks later are invalid due to a bug or an attack and we want to find the most recent "valid block" (based on the attack or the bug) to fork off

**Comment by bkase** [comment]
Unfortunately, we really do need to support blocks later than k in the common case. I think in 99%+ of cases in the real world virtually all the block producers will actually agree on many blocks later than the `k_th` one.

Can you think about what sort of tooling we may want to build that can help us figure out what this block is? What do we need to log? What do we need to visualize from logs that we can ask people to run? etc.
