### ISSUE TITLE
Crashed when run Coda daemon kimziv#2691

### ISSUE THREAD

**Issue by kimziv** [MinaProtocol/mina#5866]
Coda daemon is booting up; built with commit "3e9b1748183e653a7891adea1fef07c8e1a7dfcd" on branch "feature/bump-genesis-timestamp"

 I just running the code daemon, then crashed, and attach the crash report /root/.coda-config/coda_crash_report_2020-09-04_23-24-34.262026.tar.gz
[coda_crash_report_2020-09-04_23-24-34.262026.tar.gz](https://github.com/CodaProtocol/coda/files/5177305/coda_crash_report_2020-09-04_23-24-34.262026.tar.gz)

My Discodrd ID: kimziv#2691

**Comment by garethtdavies** [comment]
@kimziv this error `Failure "no seed or initial peer flags passed"` is caused because there is no current active network to connect to. You will need to wait until the launch of 3.3 to connect to a public testnet or alternatively use the [sandbox node ](https://codaprotocol.com/docs/developers/sandbox-node) to run a private network. See the #announcements channel in Discord for more.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
