### ISSUE TITLE
QA time locked accounts

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#5993]
Test block production with timed accounts (Currently timed-locked accounts can be created only in genesis ledger)
Having locked tokens changes the coinbase amount and this in turn affects the blockchain snark. We should test if new snarked ledgers are created with transactions (user and coinbase transactions) on these timed-locked account. This would mean running a qa net long enough to emit proofs from the scan state. `just_emitted_a_proof` in the logs tell whether a block has a new snarked ledger.

**Comment by psteckler** [comment]
The existing unit tests in `Transaction_snark` compare the checked and unchecked timing validations.

Validation takes a (timed) account, a transaction amount, and a global slot, and returns a new timing (perhaps `Untimed`) or an error. If there's no error, validation succeeds, and the transaction can proceed.

"Fully-vested" means the calculated min balance is zero. The situations considered in the existing tests are.

- Valid cases:	
	- before the cliff time, still timed
	- past the cliff, the min balance is still greater than zero, so still timed
	- fully-vested, so now untimed
	- fully-vested, can spend whole balance

- Error cases:
	- past the cliff, transaction amount would reduce balance below min balance, an error
	- past the cliff, transaction amount exceeds actual balance, an error

**Comment by psteckler** [comment]
Possible new unit tests: compare the calculated min balances in checked, unchecked worlds before/after cliff, after full vesting.

Possible integration tests: send payment with timed account, with amounts that would, would not take balance below minimum. Should see `applied` status for success, `source insufficient balance`.

(All timing validation errors map to insufficient balance, apparently, though some should be something like "insufficient available balance due to timing".)

**Comment by aneesharaines** [comment]
Worked out a way to deal with expected errors
