### ISSUE TITLE
Tags for coda-archive, coda-daemon, and deb package are all slightly different. Some have commit hash, some have branch name, some have neither

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6127]

**Comment by lk86** [comment]
The attached PR solves a few problems at once. Uploading multiple copies of the same image does not cost much time or money, so I've just updated it so that each image is tagged both with the commit tag and without. This allows for a dynamic image tag when this is useful, as well as a very specific tag when you want a stable image at a specific commit.
