### ISSUE TITLE
Daemon existing issue

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [MinaProtocol/mina#6434]
On totally clean machine, Daemon exists after few hours. The coda-log.txt is attached.

The hardware configuration of the node is as follows:
CPU: Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz (56 cores)
Memory: 128G

[coda-log.txt.tar.gz](https://github.com/MinaProtocol/mina/files/5405952/coda-log.txt.tar.gz)

**Comment by StarLI-Trapdoor** [comment]
[coda-log.txt.tar.gz](https://github.com/MinaProtocol/mina/files/5413565/coda-log.txt.tar.gz)

The issue happens again.
More logs are attached.

**Comment by nholland94** [comment]
Neither of your logs seem to indicate a crash. It's possible that your daemon ran out of memory or segfaulted, and was immediately killed by the OS. With 128G RAM though, OOM seems unlikely., Check if there is a core dump available and upload that if you can find one. Also, these logs that were uploaded are from the stdout of the daemon, but in order to properly debug issues like this, we need to raw json log, which you can find in '~/.coda-config/coda.log`.

I'm going to close this issue for now, as there is nothing actionable we can do with the current information, but if you can reproduce this and upload the json log file (and a core dump if there is one), then feel free to reopen this or create a new issue and we will take a look at it.
