### ISSUE TITLE
Add missing failures to Transaction_snark.Base.User_command_failure.t

### ISSUE THREAD

**Issue by psteckler** [MinaProtocol/mina#6450]
The constructors of that type should match those in `Coda_base.User_command_status.Failure.t`.

There are some missing cases.

**Comment by psteckler** [comment]
Should that module just be aliased, so they're always in synch?

**Comment by mrmr1993** [comment]
There is no technical reason to do this: the logic in the snark matches the logic outside of the snark, and the two kinds of failure never interact. Doing this also unnecessarily inflates the size of the snark.

However, I'm a fan of paying down technical debt: we should do #6050 and then consume the `User_command_failure.t` directly, so that we don't have 2 parallel concepts and implementations.

Perhaps, though, we should shelve #6446 until #6050 is done.

**Comment by psteckler** [comment]
Yes, having just one type for the possible failures sounds like the right solution.
