### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by bidulemachin** [MinaProtocol/mina#6492]
[coda_crash_report_2020-10-23_12-09-44.520855.tar.gz](https://github.com/MinaProtocol/mina/files/5429379/coda_crash_report_2020-10-23_12-09-44.520855.tar.gz)

complete log file here :
https://drive.google.com/file/d/1iiP6g4AMpXjmAhIHnOy5dJp9Z63yCO--/view?usp=sharing

**Comment by nholland94** [comment]
This is the error from the crash:
```
(monitor.ml.Error
  (runtime-lib/runtime.ml.E "predicate failed"
    ((Value -NAN) (Loc src/lib/trust_system/peer_trust.ml:164:23)))
  ("Raised at file "runtime-lib/runtime.ml", line 28, characters 28-53"
    "Called from file "runtime-lib/runtime.ml" (inlined), line 57, characters 4-53"
    "Called from file "src/lib/trust_system/peer_trust.ml", line 164, characters 23-30"
    "Called from file "src/deferred0.ml", line 56, characters 64-69"
    "Called from file "src/job_queue.ml" (inlined), line 131, characters 2-5"
    "Called from file "src/job_queue.ml", line 171, characters 6-47"
    "Caught by monitor coda"))",
  "Command": "Command: (coda daemon -peer
 /dns4/seed-two.pickles-public.o1test.net/tcp/10001/p2p/12D3KooWFcGGeUmbmCNq51NBdGvCWjiyefdNZbDXADMK5CDwNRm5
 -peer
 /dns4/seed-one.pickles-public.o1test.net/tcp/10001/p2p/12D3KooWJ9mNdbUXUpUNeMnejRumKzmQF15YeWwAPAhTAWB6dhiv
 -peer
 /ip4/35.243.238.16/tcp/10001/p2p/12D3KooWAFFq2yEQFFzhU5dt64AWqawRuomG9hL8rSmm5vxhAsgr
 -config-file /home/machin/daemon.json -generate-genesis-proof true -log-json
 -log-level Trace -block-producer-key /home/machin/keys/my-wallet)
```

This appears to be a bug with the trust system, which is actually not used at the moment. A fix for this was put in place already, and will be included in the next release of the daemon. https://github.com/MinaProtocol/mina/commit/58614d396ec1b21e868aa68213564c9784537cb7#diff-2f891f6d56f43fde83125e14d90f9ec4c101e1b635efb9863b99ec0deb0275b3

FYI, the archive you uploaded is titled `*.zip`, but it's actually a gzip'd tar archive, which should be `*.tar.gz`. Took me a little bit to figure out how to actually extract it because of this, since unziping this results in an error.
