### ISSUE TITLE
Communicate hardware requirements more clearly for 4.1

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#6560]
Contabo VM (german cloud provider) users are not producing blocks + broadcasting in time, even with 8 cpu cores + 32gb ram. Should we make the network parameters more forgiving for 4.1?

**Comment by Igor-Tselkovskiy** [comment]
The same situation does not produce a block, although it has been working on contabo for a year and there was no such problem.
{
  "timestamp": "2020-11-02 08:20:51.987989Z",
  "level": "Error",
  "source": {
    "module": "Coda_lib",
    "location": "File \"src/lib/coda_lib/coda_lib.ml\", line 1188, characters 26-53"
  },
  "message": "Internally generated block $state_hash cannot be rebroadcast because it's not a valid time to do so ($timing)",
  "metadata": {
    "external_transition": {
      "data": {
        "protocol_state": {
          "previous_state_hash": "3NLF2QUKCb4itiJ5KNXpA9WNpSET6eief1U7zcxYa72ePA8E9Rem",
          "body": {
            "genesis_state_hash": "3NLem1gvtcM2WbA8Xwd6kJEMXkkjTeKZvKvDZZUsWU8E9DU9r1pw",
            "blockchain_state": {
              "staged_ledger_hash": {
                "non_snark": {
                  "ledger_hash": "jxvqAhrVTPrr8r7CpwFTHQsaACLYsic9FqnjTqBsAqpCZr9xDa4",
                  "aux_hash": "VKqSPzmaBcX8kunXmdzePp5LU7q3fJ9vjWnDFmWS3DKHDQaAQk",
                  "pending_coinbase_aux": "XUiL44dnuq6YcZo8JdUkV9GueeFfCsrhJ6B28Cjv5xwf68Q2vN"
                },
                "pending_coinbase_hash": "2mzohxzNyJzKX7h6UruE5W2uaLeCyXKjeu9Kt1TnZiBgihrY9axx"
              },
              "snarked_ledger_hash": "jx3PPhEXjWwQDTXq3x9ArrDgDp6Tcu9xnB9yJmTa4ZnFJdvvrsg",
              "snarked_next_available_token": "2",
              "timestamp": "1604305062000"
            },
            "consensus_state": {
              "blockchain_length": "383",
              "epoch_count": "0",
              "min_window_density": "77",
              "sub_window_densities": [
                "0",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7",
                "7"
              ],
              "last_vrf_output": "13IeKjBYTwVam-UoCKSNDP3FBYiDG5hc6fjpIAlNhwA=",
              "total_currency": "5134826000001000",
              "curr_global_slot": {
                "slot_number": "1026",
                "slots_per_epoch": "7140"
              },
              "staking_epoch_data": {
                "ledger": {
                  "hash": "jxC1MKc8BdvutxJb2XnLX7Kf3BoSNpRgYzim3RMcnRV7mYfws9M",
                  "total_currency": "5044026000001000"
                },
                "seed": "2va9BGv9JrLTtrzZttiEMDYw1Zj6a6EHzXjmP9evHDTG3oEquURA",
                "start_checkpoint": "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x",
                "lock_checkpoint": "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x",
                "epoch_length": "1"
              },
              "next_epoch_data": {
                "ledger": {
                  "hash": "jxC1MKc8BdvutxJb2XnLX7Kf3BoSNpRgYzim3RMcnRV7mYfws9M",
                  "total_currency": "5044026000001000"
                },
                "seed": "2vbzrrqw1F14bWv9cUAG5hgvwzHbDJfy4jRAdFi8u6mLZyZwsj1s",
                "start_checkpoint": "3NK2tkzqqK5spR2sZ7tujjqPksL45M3UUrcA4WhCkeiPtnugyE2x",
                "lock_checkpoint": "3NLF2QUKCb4itiJ5KNXpA9WNpSET6eief1U7zcxYa72ePA8E9Rem",
                "epoch_length": "384"
              },
              "has_ancestor_in_same_checkpoint_window": true
            },
            "constants": {
              "k": "290",
              "slots_per_epoch": "7140",
              "slots_per_sub_window": "7",
              "delta": "0",
              "genesis_state_timestamp": "1604120382000"
            }
          }
        },
        "protocol_state_proof": "<opaque>",
        "staged_ledger_diff": "<opaque>",
        "delta_transition_chain_proof": "<opaque>",
        "current_protocol_version": "0.1.0",
        "proposed_protocol_version": "<None>"
      },
      "hash": "3NLmD3f47S4cxro92LgJMKasMetTabdg48v8MM4nKA4A4JXcm2CQ"
    },
    "host": "62.171.184.84",
    "peer_id": "12D3KooWJvbGCEUN5HQ4UfCtVu4LJiGPHMGMMREyvw2AaBCEkcYi",
    "pid": 23795,
    "port": 8302,
    "state_hash": "3NLmD3f47S4cxro92LgJMKasMetTabdg48v8MM4nKA4A4JXcm2CQ",
    "timing": "0 slots too late"
  }
}

**Comment by aneesharaines** [comment]
Need to reprofile after memory leak fix is in

**Comment by EmrePiconbello** [comment]
Contabo can't provide stable service for mina. The snark works and block production hit CPU limits under most circumstances. Since contabo is shared I don't think it's ever going to be a stable option for mina chain. Especially after mainnet not to mention using them for mainnet is a big security risk.

**Comment by Igor-Tselkovskiy** [comment]
> Contabo can't provide stable service for mina. The snark works and block production hit CPU limits under most circumstances. Since contabo is shared I don't think it's ever going to be a stable option for mina chain. Especially after mainnet not to mention using them for mainnet is a big security risk. On the other hand, forgiving network requirements will be better for testing and future process. With much lover spec requirement, everyone can easily run the nodes and provide that for the testphase instead of going for shared and not optimal ways, In the result of that we will have more stable and durable testnet.


And how then to explain the fact that since testnet 2.1, it coped well with the production of blocks and such a problem did not arise. Moreover, many users use it.

**Comment by EmrePiconbello** [comment]
Probably the node was not that intensive earlier. My comment was about contabo being shared and never going to be a reliable solution. In testnet it wasn't intense it was passive network without transaction so out of every 5 only missed 1 block. When chain resource requirements increase and become more intensive because of transactions on meempool, transaction numbers, number of nodes etc. Contabo is going to be less reliable miss 3 out of every 5.  According to logs, It's not fast enough for the existing network parameters.
