### ISSUE TITLE
 QA Net ( coda-testnet-postake-medium-curves=0.0.16-beta7+-pre-release-blocktime-increase-db1ee8b)

### ISSUE THREAD

**Issue by ghost** [MinaProtocol/mina#6566]
![Screenshot_4](https://user-images.githubusercontent.com/73755459/97786323-b3324480-1ba2-11eb-8266-94ef47d3e5c6.jpg)

Issues caused by installing third party software addons to existing node i.e htop.
Issue resolved by removing or installing plain.

**Comment by garethtdavies** [comment]
Also see #6560 

To give more context on this issue, blocks were not being broadcast on a Contabo VPS due to them not being produced in time. This shows up in the logs as `Internally generated block $state_hash cannot be rebroadcast because it's not a valid time to do so ($timing)`.

@Nightguy1688 It's unlikely something like `htop` has any impact on this but more that the Contabo VPS is simply not fast enough to produce a block in time given the current testnet implementation. Running additional programs certainly won't help this case though.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
