### ISSUE TITLE
what data should we sync with bitswap?

### ISSUE THREAD

**Issue by emberian** [MinaProtocol/mina#6570]
i think we should sync at least:

- [ ] block data
- [ ] scan state

others? pool data (transaction data)? smart contract state?

**Comment by deepthiskumar** [comment]
pending coinbase, local state sync (epoch ledgers)?

**Comment by nholland94** [comment]
Would we push our sync ledger logic onto bitswap, or would we keep it how it is? If we are fine with sync ledger the way it is now, we can use that mechanism for local state sync instead of bitswap (local state == 2 ledgers). Currently, we just binio the entire ledger, but the plan was to move that over to use sync ledger (doable now with some of the work we did for epoch ledger persistence).

Pool synchronization sounds like a candidate, though it's something we don't have at all atm. We would need to think about how that would be keyed in the bitswap world.

FWIW, I believe the protocol state itself can be broadcast and potentially even requested outside of bitswap. The portion of the block we would certainly want to download via bitswap would be the staged ledger diff of the block. However, it may be worthwhile to provide fixed buckets of protocol states over bitsync for catchup and bootstrap. For instance, every N blocks of a chain can be bundled under a single bitswap key, allowing nodes to sync to lots of blocks quickly. I can provide more details around how this could actually work if others are interested.
