### ISSUE TITLE
Command "coda client cancel-transaction" failed

### ISSUE THREAD

**Issue by crackerli** [MinaProtocol/mina#6605]
**How to produce:**
**1**. create a transaction
**2**. use "coda advanced pooled-user-command" to get the id, like below:

[{"id":"G8k9HJXpug4J51mXSsxue3uAiriZfA7F6qJAYgoLNYqpo7Pz6XX9GNWAGBmNg5PnZTqHrmA7WaQnpXwR6C1xDQBVVi3EmYyZn4s2WicHLTwPrkMaUfoPpkveyxDUq9se4xca1B67LzXaULJ64Ktpxu7g2YbfsHzG2EUFcqp7yee96rJeJ84BuYj3BAnx9SzvWEnSaphCvtquKwugD8kCDkAfzFg5QpGgQSvF7YoeMysBsHwks3rTaGaendFtKP3dm4CdWN7CypkaowqZbzsgtgFQpYc1ETg3KS5rTvPRyvN3NhvEYt2CmmzjzMVxVeBgrcp7H2hC5KHWLiPm3gcnbsdr1LNRTPmyJpubpjTzzTz1fB4gUoCuZN8mqJtDdRrW72B915WKc","isDelegation":false,"nonce":0,"from":"B62qkFeY1vNgDLu69NZV8m7mjrK3ukThADWPf6UqgogRYxuzZurUewB","to_":"B62qmXNWo8gkpRCceWwAHtrHKUHctwpmtgtnXy49fmCqLumLPQDUquZ","amount":"1.11","fee":"0.01","memo":"E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"}]

**3**. use the id above to execute command "coda client cancel-transaction -id <ID>", then get the following error:
Fee to cancel transaction is 5.01 coda.
Error: Couldn't send user_command: Error creating user command: {"payload":{"common":{"fee":"5.01","fee_token":"1","fee_payer_pk":"B62qkFeY1vNgDLu69NZV8m7mjrK3ukThADWPf6UqgogRYxuzZurUewB","nonce":"0","valid_until":"4294967295","memo":"E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"},"body":["Payment",{"source_pk":"B62qkFeY1vNgDLu69NZV8m7mjrK3ukThADWPf6UqgogRYxuzZurUewB","receiver_pk":"B62qmXNWo8gkpRCceWwAHtrHKUHctwpmtgtnXy49fmCqLumLPQDUquZ","token_id":"1","amount":"0"}]},"signer":"B62qkFeY1vNgDLu69NZV8m7mjrK3ukThADWPf6UqgogRYxuzZurUewB","signature":["Keypair","B62qkFeY1vNgDLu69NZV8m7mjrK3ukThADWPf6UqgogRYxuzZurUewB"]} Error: Input nonce 0 different from inferred nonce 1 (in ["sendPayment"])

**This error can found in both QA-net and pickles-sandbox.**

**Comment by nholland94** [comment]
This issue arises when we convert a `User_command_input.t` into a `User_command.t` in the transaction pool. The offending code is here https://github.com/MinaProtocol/mina/blob/develop/src/lib/user_command_input/user_command_input.ml#L38. It appears as though this logic was put in place in order to let users know when the nonce they are submitting for their user command is not valid against the current known set of transactions in the node's pool. From a UX perspective, I'm not totally sure what the correct thing to do here is, since I imagine this is a check we still want in those cases. That said, I can also see an argument where users may prefer to optionally have full control over the nonces they set in user commands so that they can enqueue future transactions or overwrite transactions at will (pretty advanced use cases though).

I think one potential solution to this would be to add an extra field to the `User_command_input.t` (and subsequently the `sendPayment` GraphQL query) to toggle this nonce assertion. When we send cancellations, this would be disabled. In the regular `coda client send-payment` CLI, we would enable this nonce assertion by default, but provide a CLI flag to disable it if the user wishes. @bkase does this sound correct?

**Comment by ronawilliamsoso** [comment]
coda client cancel-transaction -id rKAkRnV1yvr54Mj5BiGLL6VwywGs1LmiyJMaEX3uoQDLayHLsokabgmDEjAZMDwjKPr19iebv2n8H1NNDKUqz3APnRvzJBx4YnQece29ei3q68tvFgoignaKK55VfMw92wm7ybsgbYPvxEHWePBKEip8j6XpysfhkAQ5D1scCB2ypu5o5iWjH9v86HXA76fyWsWQfKTKuDNtG2kuhADMCzErwgLTcZRfgqJ3W4abDicCuYjJcgnG4SRYZF1eN9dLCZkYj8fQrV4h1brfv6NFXaANtCnoXzfSDzMfyLHz4vAB33LE9ZAt3rghkBFaanG6qgTW3hgRHVzdi7ecAS6BiMRNS95VqgTsyACWpAeEAAAvjMNy2tqhhqxbm3zWiKvSNUvEHX42ewVEbEfJXTtcP
Fee to cancel transaction is 305 coda.



❌ Error: Couldn't send user_command: Error creating user command: {"payload":{"common":{"fee":"305","fee_token":"1","fee_payer_pk":"B62qkgnXnQ2WtesZoJyPGiHLtiCJWPTht5NDbncdZmYYVp7ux2kgyto","nonce":"6","valid_until":"4294967295","memo":"E4YM2vTHhWEg66xpj52JErHUBU4pZ1yageL4TVDDpTTSsv8mK6YaH"},"body":["Payment",{"source_pk":"B62qkgnXnQ2WtesZoJyPGiHLtiCJWPTht5NDbncdZmYYVp7ux2kgyto","receiver_pk":"B62qoWjj77gk6UD55nAPMr8NeTwVgXGiannrZ34cmfjamuJjG3YNH5K","token_id":"1","amount":"0"}]},"signer":"B62qkgnXnQ2WtesZoJyPGiHLtiCJWPTht5NDbncdZmYYVp7ux2kgyto","signature":["Keypair","B62qkgnXnQ2WtesZoJyPGiHLtiCJWPTht5NDbncdZmYYVp7ux2kgyto"]} Error: Input nonce 6 different from inferred nonce 7 (in ["sendPayment"])

**Comment by mrmr1993** [comment]
This was fixed in #7346. Closing.
