### ISSUE TITLE
Profile memory usage in catchup

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6642]

**Comment by mrmr1993** [comment]
A significant part of this is likely to be held in the cache ([implemented here](https://github.com/MinaProtocol/mina/blob/develop/src/lib/cache_lib/impl.ml)). If so, we might benefit from writing the cache to disk and holding only a subset of it in memory.

@ghost-not-in-the-shell It may be worth examining the memory usage of the cache directly. You can use `Obj.reachable_words (Obj.obj x)` to show the memory footprint of a value `x` in the OCaml heap. Note that this may be slow if the object is large, since it needs to recursively walk each object to discover the total size, so you may want to limit how often it gets called.
