### ISSUE TITLE
Status stuck in CatchUp since more than 24 hrs

### ISSUE THREAD

**Issue by cryptoenthu1** [MinaProtocol/mina#6660]
PF coda-log.txt : https://drive.google.com/file/d/1sPokA0lRnaCJ0szAboCtFnX17BJf7KFI/view?usp=sharing

Coda client status : https://drive.google.com/file/d/1OUUawiybHpX0ySYebO7o69uzvNrVmDap/view?usp=sharing

**Comment by nholland94** [comment]
Looking at the logs, it appears as though there was a large initial catchup the node had to do, but once that completed, the node was actually synced to the chain (which you can also see in the status output since the best tip block height == the max observed block height). The logs do indicate a lot of short fork catchup jobs that occurred, which is why the daemon keeps on reporting that it's in catchup even though it is essentially synced to the chain. I think this is a combination of the testnet parameters now being set to `delta=0`, along with the outstanding issue to only surface catchup status in the case of longer catchups, captured here #4165. I will leave this open for now since #4165 is work ticket and not a bug ticket, but we should close this once that work is done and we verify this behavior is fixed.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
