### ISSUE TITLE
Investigate pickles-public network fork

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#6735]
The network health checks indicate that the pickle-public network is forked at length > k.

**Comment by ghost-not-in-the-shell** [comment]
After looking through the network health report, I didn't find any forks that need particular attentions.

There were small forks caused by nodes producing blocks before initial catchup finished. But those usually won't last long.

On 11/15 there were 2 nodes stuck at catchup for a long time (almost a day), but they didn't cause any unrecoverable fork.
