### ISSUE TITLE
Setup develop for stable chain id

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#6737]
We want to have a temporary stable chain id setup for our develop branch (at least up until the 4.1 hard fork). Current plan is to implement a health check on develop CI which will connect the build to the running `pickles-public` network to see if it is still compatible.

**Comment by mrmr1993** [comment]
* The additional check to prevent type changes landing in develop has been merged in #6742
* The bash script to connect to the current testnet as a CI job is in a branch [here](https://github.com/MinaProtocol/mina/tree/feature/ci-connect-to-testnet)
  - The dhall code to run the script on buildkite still needs to be written. I'm punting this, since I'm not familiar with our buildkite/dhall setup.
