### ISSUE TITLE
Crash when generating crash report

### ISSUE THREAD

**Issue by pkrasam** [MinaProtocol/mina#6788]
command executed
`coda client export-local-logs`

logs from recent crash
[exported_logs](https://drive.google.com/file/d/1MrPkXbnZOBlPMnH9eqqiHvZZXEDunneq/view?usp=sharing)

**Comment by bkase** [comment]
Is this a memory issue? In any case, did we end up landing the fixes 

@pkrasam How much CPU / RAM are you running with?

**Comment by bkase** [comment]
Also made #6799 so we don't need to ask this question again

**Comment by pkrasam** [comment]
@bkase the machines has enough CPU, RAM, SSD
## block-producer
- CPU: 12 cores, 24 threads
- RAM 128 GB
- SSD 2 TB
- CPU utilisation is sitting at 10% - 15%
- RAM utilisation is sitting at 10%

**Comment by nholland94** [comment]
Your node shutdown because `libp2p_helper process died unexpectedly: died after receiving sighup (signal number 1)`. On linux (as far as I can tell) sighup is only sent to a process when the virtual terminal or ssh session running the shell shuts down. This seems to indicate that you were not running the daemon in the background, but instead may have been running it in the foreground from a shell that was destroyed.
