### ISSUE TITLE
Why does our network health script report vastly different numbers of live nodes over short time periods? (bkase)

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#6984]
Are nodes actually crashing and restarting frequently? Also is it undercounting? Grafana is stable
-- Mark when nodes are down
-- Get the statuses for each thing

**Comment by imeckler** [comment]
According to @bkase, the last time we discussed this there were several hypotheses but no definite understanding.

@psteckler suspects fluctuation is due to a fraction of nodes errors (heartbeats, timeouts, etc.). There is a version of the script (which is not yet running on the turbo-pickles testnet) that will classify errors more granularly. We don't know the causes of those errors though. Both @psteckler and @bkase guess this is due to the queried nodes being busy working on something.

**Comment by aneesharaines** [comment]
Need to update the network health reports to use the uptime being reported by the telemetry rpc @es92

**Comment by EmrePiconbello** [comment]
I am monitoring our end for a while the testnet 4.1 was not reporting correctly most of the time and have issues. Testworld started well till Jan 1 12 am since then it's very unstable to respond and over 1 second. There are several times it passed 10 seconds which I put as a limit to respond in this week-long chart the spikes are not visible 
![image](https://user-images.githubusercontent.com/54602437/103705326-c1398280-4fa2-11eb-9aec-43391a0eedc8.png)
