### ISSUE TITLE
[Bazel]: fixup nits from #7146

### ISSUE THREAD

**Issue by mrmr1993** [MinaProtocol/mina#7152]
These are
* [ ] Fixing a commit for obazl
  - this needs to be done soon, to ensure that checking out a commit and building with bazel can be done despite upstream changes
  - easy fix, agreed to do in a follow-up PR
* [ ] Using submodules instead of remote repo URLs + commits
  - submodules haven't all been updated yet, so this can wait for that
* [ ] Mac builds using `staticlib`
  - easy fix, non-urgent
* [ ] Deleting some unused code
* [ ] Documentation on some bazel-specific bash scripts

See PR #7146 for more detail. @mobileink will be working on these.

**Comment by mobileink** [comment]
OBazl rules pins:

While we are still merging/integrating/testing the Bazel code into the Bazel branch, the obazl rules will be pinned to the main branch rather than specific commits.  This is just for convenience, so that any changes to the obazl rules we may need to make will be automatically used. This transition period should be quite short, a matter of a day or two. Once all Bazel code has been merged into the Bazel branch, and the builds have been verified on MacOS and Linux, these repos will be pinned to specific commit IDs.

The repos affected are obazl_rules_opam, obazl_rules_ocaml, and obazl_tools_bazel. They are loaded by the `ocaml_fetch_rules` function in `WORKSPACE.bzl`.

**Comment by mobileink** [comment]
Submodules:

As for pinning, during the transition period the code will use remote repositories to fetch the code, rather than the embedded git submodules. Again this is just a convenience, in case we discover that we need to make changes to any of the external repos, and it will only apply during the short window of transition.  Once all Bazel code is integrated and builds are verified, we will switch to using `local_repository` rules that resolve to the embedded git submodules, which will be pinned to specific commit IDs.

The code supporting remote repos will be retained since it will be used if and when a decision is made to remove git submodules.

The affected repos are:

* ppx_optcomp
* ppx_version
* snarky
* graphql_ppx
* marlin
* zexe

Special cases:  ocaml-rocksdb and ocaml-sodium

The code that loads the repos is in `bzl/external/ocaml_repos.bzl` and `bzl/external/rust_repos.bzl`.

**Comment by mobileink** [comment]
Link modes: see #7155
