### ISSUE TITLE
Adverserial Testnet Challenges

### ISSUE THREAD

**Issue by figitaki** [MinaProtocol/mina#7222]
We need to update the Leaderboard logic to support tiered rewards. Each challenge now needs to support the following tiers:

* 1st place
* 2nd place
* 3rd place
* Top 10
* Top 100
* Top 200

Fortunately, we only have three automated challenges for adverserial:

1. Produce Blocks (Ranked by most blocks produced)
2. Produce and Sell SNARKs (Ranked by number of SNARKs included in a block)
3. Send Transactions (Ranked by number of txns included in blocks)

Please see the Figma designs for full details on each challenge:
https://www.figma.com/file/vyGC2DCKTBFDR6HIkHt6sK/Testworld?node-id=5337%3A47383

**Comment by bkase** [comment]
Looks like a lot of this infrastructure is already in place!

The tiering is supported via the `Points.applyTopNPoints`

1. Produce blocks is basically `Challenges.bonusBlocksChallenge`
2. I think this should change to the existing `snarkFeesCollected` metric otherwise the economics encourage weird behavior, (asking in our internal channels)
3. This is handled by `transactionSent`
