### ISSUE TITLE
Some nodes get stuck in "connecting state" after having already synced. Maybe correlated with high peer count issue?

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7294]

**Comment by ArtemBernatskyy** [comment]
@es92 any news/updates on this one?

**Comment by es92** [comment]
Have you been seeing it? I've only observed it so far on nodes internal to our cluster, can you dm me your `coda client status`?

**Comment by Syd-ai** [comment]
Hello @es92, was trying to help some guys over the discord, and indeed this issue seems to be more and more frequent.
Advice was generally to download last peers + restart node, and it seems to work generally
Here's some coda client status screenshots

![image](https://user-images.githubusercontent.com/58671114/103454042-2ad63a00-4ce0-11eb-8c73-1897f5caae3b.png)
![image](https://user-images.githubusercontent.com/58671114/103454054-548f6100-4ce0-11eb-8160-9b61401d710c.png)
![image](https://user-images.githubusercontent.com/58671114/103454060-63761380-4ce0-11eb-84a3-8a06e009a901.png)
![image](https://user-images.githubusercontent.com/58671114/103454064-70930280-4ce0-11eb-9137-dd20e4e305ad.png)
![image](https://user-images.githubusercontent.com/58671114/103454085-8ef8fe00-4ce0-11eb-8781-ed88c2d6952e.png)

**Comment by bkase** [comment]
I just refreshed the peers list so maybe that will help some of these connecting issues folks are seeing -- though it could also be related to the high peer count.

**Comment by garethtdavies** [comment]
Couple more recent reports of this in Discord e.g. https://discord.com/channels/484437221055922177/746316198806814760/795144259434840064

**Comment by BostonMike0643** [comment]
Gareth, I hadn't been watching number of peers, but I have routinely been in the 70-80 peers connected.

**Comment by ArcadeMachinist** [comment]
Same here, node disconnected after block 364, has 49 peers, few hours in "Connecting".
Daemon restart helps.

**Comment by ghost-not-in-the-shell** [comment]
Nodes would be `connecting` if they are considered `offline`. It could be that the online status is broken.

**Comment by ghost-not-in-the-shell** [comment]
Another possibility could be that the node actually never received any gossip message. `connecting` status is triggered once it got some libp2p peers. After looking at the online status code, I think this situation could be higher possibility than online-status is broken.

**Comment by aneesharaines** [comment]
@es92 - do you know if this was fixed by super catchup?
