### ISSUE TITLE
Verify VRF winnings for the given slots + discuss multi-blocks in same slot logic

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7311]
According to this data, this account has won 5 slots over the last few days. Did it really win these slots? 

Moreover, this same public key has produced 14 blocks on different heights within these 5 slots, should we punish this behavior?

<img width="1533" alt="Screen Shot 2021-01-04 at 5 03 46 PM" src="https://user-images.githubusercontent.com/515445/103554241-93f2b480-4e7c-11eb-829f-2db4cbd11dd9.png">

https://minaexplorer.com/wallet/B62qoE9wDH7RWW6sAqPQJ5KFEkypLt3cH4DeuJTsieQY5gxNYsbEuNT/blocks

**Comment by bkase** [comment]
I think if we can get away with it from a correctness perspective, it would be best for nodes to only punish others if they receive, lets say more than 3 blocks for the same slot. This buffer would give folks some breathing room if they're worried about their primary-replica systems malfunctioning (anecdotally, I've heard this has caused some validators to be slashed on other networks in the real world)

**Comment by EmrePiconbello** [comment]
I can say if the block were legit I don't see a reason for slash or punishment. I only see he is running multiple block producers at once. Normally other pos networks never allow those actions since all consensus/block producing peers are connected to each other. On mina that can be achieved and it's in a way considered as an attack on the network. Every pos network I know counts these double sign attempts as an attack. Under any circumstances, since all the extra nodes just create an orphan block and could cause issues I think some kind of slashing/punishing can make sense. Also, half of these blocks came from not synced.

**Comment by bkase** [comment]
> it would be best for nodes to only punish others if they receive, lets say more than 3 blocks for the same slot. 

Note that it is important to wait for the entire slot before making the banning judgments to account for folks running nodes in different regions and positions in the gossip network. And it's important for all nodes to have as consistent a selection as possible for the canonical chain. Moreover, each node should remember how many blocks it has seen from the same creator to prevent creating too much unnecessary traffic.

Suggested logic:
At the end of every slot, look at all the blocks that were sent to us for this slot. If more than 3 blocks were from the same block creator (a) insta-ban the creator and (b) if any specific sender forwarded more than 3 blocks from the same block creator insta-ban that sender.

**Comment by bkase** [comment]
Upon further discussion with @EmrePiconbello , 2 should be more than enough. Folks shouldn't need to run more than one replica live at the same time.

**Comment by deepthiskumar** [comment]
This seems to be normal. @imeckler ran vrf evaluations for some keys to determine how many slots each won. Here's some pks with balance `66000` and the slots won

```
{"basename":"extra_fish_account_992","slots_won":["1128","2204","2447","4366","4423","4496","4517","4840","5318"]}
{"basename":"extra_fish_account_991","slots_won":["85","3705","4662","4726","6606"]}
{"basename":"extra_fish_account_990","slots_won":["375","2223","3485","5671","6380"]}
{"basename":"extra_fish_account_99","slots_won":["1808","2268","4462","6711"]}
{"basename":"extra_fish_account_989","slots_won":["175","959","2367","2785","3304","4025","6336"]}
{"basename":"extra_fish_account_988","slots_won":["1621","2782","4241","4763"]}
{"basename":"extra_fish_account_987","slots_won":["685","1441","2285","3489","4788","4895","6028","6097"]}
{"basename":"extra_fish_account_986","slots_won":["4191","4227","4335","4653","5510","6066","6745"]}
{"basename":"extra_fish_account_985","slots_won":["2423","2572","2765","3172","5096","5736","6256","6373","6603"]}
{"basename":"extra_fish_account_984","slots_won":["1169","1421","2118","3206","3596","5031","5725","6462"]}
{"basename":"extra_fish_account_809","slots_won":["238","889","1108","1322","2015","2470","2518","2928","3071","4121","5711","6637","7130"]}
```

Accounts do win more than 5 slots and the last one (`extra_fish_account_809`) won 5 slots in the timeframe similar to the account in this issue https://minaexplorer.com/wallet/B62qoE9wDH7RWW6sAqPQJ5KFEkypLt3cH4DeuJTsieQY5gxNYsbEuNT/blocks

**Comment by deepthiskumar** [comment]
Regarding punishing for multiple blocks for the same slot, I can’t think of a viable attack. We have a tie breaking rule for blocks that are produced by the same producer and for the same slot (comparing protocol state hash) so there won’t be a fork as a result of this behavior and it is going to be an expensive DDOS attack to produce a lot of valid blocks for a slot. @nholland94 any thoughts on this?

Re producing blocks before fully catching up, it is captured here https://github.com/MinaProtocol/mina/issues/7005 and https://github.com/MinaProtocol/mina/issues/4150 and we should probably fix it before main net

**Comment by nholland94** [comment]
We've had a long running conversation around this multiple blocks by same proposer in the same slot issue, which is often coined the "nothing-at-stake" problem. We had a meeting last month where we came to a decision to copy what Cardano is doing to solve this problem. Namely, if we get multiple blocks by the same proposer in the same slot, we must broadcast all of those blocks, but that we implement a deterministic tie breaker in our selection rules. This way, the entire network will see all those blocks, and all nodes which have will all select the same chain. See the issue here for some more details https://github.com/MinaProtocol/mina/issues/3866#issuecomment-740060460.

Punishing or otherwise rejecting this behavior could open the doors for adversaries to fork the network by manipulating different nodes into selecting different blocks. Solving it by consistently broadcasting all blocks, and changing the selection rules so that the same block is selected by all nodes, makes this attack vector insignificant.

In terms of a DDOS, it is indeed a pretty expensive DDOS attack to perform. If it becomes an issue, we can always update our rebroadcast logic to only rebroadcast chains of a certain competitive strength. Doing that would severly limit the window in which an adversary can produce valid-to-broadcast blocks in bulk, making the attack even more costly to perform.

**Comment by rakhmanovr** [comment]
https://minaexplorer.com/wallet/B62qnfqxFnjr6nnA1x9nLGtBYLVtW95pEkT5gj5HbZMxCS49t42vW64/blocks

one more person is using this "feature" already. i think team should make some statement in terms of block challenge... otherwise it makes no sense at all, lot of people will start cloning their block producers to make more false blocks and gain points for this.

**Comment by bkase** [comment]
@rakhmanovr we are fixing the points logic only takes _one block_ per block creator for a given slot into account. In other words, you will not gain an advantage for "abusing" the feature. No worries 👍

**Comment by EmrePiconbello** [comment]
@nholland94 I suggested penalty system considering it can be categorized as an attack while It was just a part of suggestion in a discussion which I step back on. Still, there is an issue with the logic network accepting all these blocks. I think suggestions will solve the issue significantly.

**Comment by rakhmanovr** [comment]
> @rakhmanovr @averquik we are fixing the points logic only takes _one block_ per block creator for a given slot into account. In other words, you will not gain an advantage for "abusing" the feature. No worries 👍

as i see, this guy still got top points for these 'fake' blocks. he has 6500 points for 16 blocks.

https://minaexplorer.com/wallet/B62qoE9wDH7RWW6sAqPQJ5KFEkypLt3cH4DeuJTsieQY5gxNYsbEuNT

https://minaprotocol.com/memberProfile?allTimeRank=342&allTimePoints=15351&phaseRank=300&phasePoints=3251&releaseRank=307&releasePoints=3250&genesisMember=false&communityMVP=false&technicalMVP=false&name=ubbedkoln%234579

**Comment by rakhmanovr** [comment]
@bkase seems like same happening here - https://minaexplorer.com/wallet/B62qr6Kv3EWFXY8z7hucbSFSPgU95j1RaHWcELQ1YpDqbd7fdfVsLqa/blocks. So some people really gets nice advantage in terms of contest using this bug :)

**Comment by garethtdavies** [comment]
> as i see, this guy still got top points for these 'fake' blocks. he has 6500 points for 16 blocks.

If you look at the blocks grouped by slot, this user still has 6 blocks. That is currently leading the challenge.

**Comment by bkase** [comment]
Closing as won't-fix as @nholland94 's explanation describes why this is not actually dangerous as is. In the meantime, we have fixed the leaderboard logic.
