### ISSUE TITLE
Automatically pull peers.txt from a URL built into the daemon or passed via CLI

### ISSUE THREAD

**Issue by lk86** [MinaProtocol/mina#7337]

**Comment by jrwashburn** [comment]
Instead of dynamic / perpetually changing peers, can a more persistent solution be adopted? (e.g. dns + generated libp2p keys, or something along those lines?) A feature was just added to get keys from a file, now also get from a URL, etc. seems to be chasing the problem of unstable seed addresses. Is there a better solution?

**Comment by lk86** [comment]
A more persistent solution is also happening in parallel (see https://github.com/MinaProtocol/mina/issues/7042 ), but we will need a system in place in mainnet for changing the "canonical" set of peers over the life of the network and it shouldn't require shutting down your node to accept an updated list, so this still has utility even if peer IDs and IPs/hostnames are constant throughout the life of a seed peer.

**Comment by mrmr1993** [comment]
This is done. Closing.
