### ISSUE TITLE
lost blocks

### ISSUE THREAD

**Issue by sazhiv** [MinaProtocol/mina#7353]
I waited 7 days to create a block, it was created in red (575 block)
Four hours later, another block was created (588 block)
And initially it was green, they counted me an award of about 13k, but then someone took it away from me.
![image](https://user-images.githubusercontent.com/77075814/103814970-72641980-5084-11eb-84f9-7e2d6c991a71.png)
my nick: sazhiv#2581
my address: B62qnYByR7kvpk8SnkU7ajHvaWpMmyNdes3xCgr7AhujqeVZzjEM12H

**Comment by olton** [comment]
Hi
On block height 599 my node generates a block. The block was green in the explorer and I was credited with 400 coins. An hour and a half later, the block turned out to be with another user and my coins were debited from the account, and the block turned red.
my nic: vadim888#0018
my address: B62qjATdfJ6Vo1SD4UnggshjJjTpcGhXmwxAAPhqY2KvYMADDXSmdng

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
