### ISSUE TITLE
about block not in canonical chain

### ISSUE THREAD

**Issue by MisterBigfeng** [MinaProtocol/mina#7405]
Please help to see, whether it is before the update, or after the block not in canonical chain  probability is  high。I don't think it's normal

**Comment by nerdvibe** [comment]
@MisterBigfeng what are the blocks that didn't get included? I'm curious to see who else has produced them.

**Comment by ghost-not-in-the-shell** [comment]
Thank you for reporting that.

There could be multiple reasons for blocks not being included in the canonical chain, for example,
1. The block producer is not `synced` when producing the block, which means the block is not produced on top of the canonical chain;
2. Due to network issue, the produced block may not be gossiped to the entire network. So other nodes doesn't know about it (even though they are all honest);
3. At any given slot, there could be multiple block producers that win that slot. Those block producers would all produce blocks at the same time, and only one of those blocks has the chance to stay in the canonical chain. As to which block to pick, the vrf evaluation determines the final winner.

For reason 1 and 2, we are working hard to improve the stability and reliability of the system. I hope those would happen less in the future.

For reason 3, it is just how the protocol is designed.

I will close this issue for now. If your block is dropped for any other reason, please re-open this issue and add corresponding details to help us debug it.

Thank you.
