### ISSUE TITLE
Coda process exited with status code 99

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [MinaProtocol/mina#7606]
Coda process exited with status code 99
2021-01-22 00:28:13 UTC [Info] Daemon child process 73 terminated after receiving signal "sigkill"
2021-01-22 00:28:13 UTC [Error] Child process of kind "Prover" with pid 73 has terminated
+ kill 13
+ '[' '!' -f stay_alive ']'
+ exit 0
+ mkdir -p .coda-config
+ touch .coda-config/coda-prover.log
+ touch .coda-config/coda-verifier.log
+ touch .coda-config/mina-best-tip.log
+ command=daemon
+ shift
+ true
+ rm -f /root/.coda-config/.mina-lock
+ coda_pid=12

**Comment by Igor-Tselkovskiy** [comment]
https://drive.google.com/file/d/16Xnt2UD3H4Fl_O0NqnW-KY3UlmCfJHif/view?usp=sharing

**Comment by Igor-Tselkovskiy** [comment]
https://drive.google.com/file/d/1vEH-zAyvL7YwCBnc6T_TdxgiCxkYDXHT/view?usp=sharing

**Comment by gnosed** [comment]
Same here:
Specs:
- 64 GB RAM
- AMD Ryzen 5 3600 Hexa-Core
- CentOS 7 running the node with docker

```
{"timestamp":"2021-01-26 06:27:02.838360Z","level":"Debug","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 181, characters 6-18"},"message":"Snark worker using daemon $addr","metadata":{"addr":"127.0.0.1:8301","pid":217,"process":"Snark Worker"}}
{"timestamp":"2021-01-26 06:27:03.070294Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 201, characters 10-21"},"message":"SNARK work $work_ids received from $address. Starting proof generation","metadata":{"address":"127.0.0.1:8301","pid":217,"process":"Snark Worker","work_ids":[495327131,255984984]}}
2021-01-26 06:27:29 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: {
  "sexp": [
    "monitor.ml.Error",
    [ "Failure", "recursive add_exn failed" ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/network_pool/indexed_pool.ml\", line 928, characters 10-55",
      "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 947, characters 28-321",
      "Called from file \"src/result.ml\", line 96, characters 19-24",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"stdlib.ml\", line 33, characters 17-33",
    "Called from file \"src/lib/network_pool/indexed_pool.ml\", line 928, characters 10-55",
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 947, characters 28-321",
    "Called from file \"src/result.ml\", line 96, characters 19-24",
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
+ echo 'Coda process exited with status code 99'
+ sleep 10
Coda process exited with status code 99
2021-01-26 06:28:18 UTC [Info] Daemon child process 73 terminated after receiving signal "sigkill"
2021-01-26 06:28:18 UTC [Error] Child process of kind "Prover" with pid 73 has terminated
+ kill 13
+ '[' '!' -f stay_alive ']'
+ exit 0
```

**Comment by c29r3** [comment]
Related #7668 #7661

**Comment by Y0Y0jojo** [comment]
Ive crashed a bunch of times over night and today with status code 99.
im running 3.2 Ghz intel i7 6 core 32GB ram macmini in docker
BRAIN-WASHED:~ partialbrain$ docker logs mina --since "24h" | grep -A 20 -B 20 exited
+ echo 'Coda process exited with status code 99'
+ sleep 10
+ kill 14
+ '[' '!' -f stay_alive ']'
+ exit 0
+ mkdir -p .coda-config
+ touch .coda-config/coda-prover.log
+ touch .coda-config/coda-verifier.log
+ touch .coda-config/mina-best-tip.log
+ command=daemon
+ shift
+ true
+ rm -f /root/.coda-config/.mina-lock
+ coda_pid=14
+ coda daemon -config-file /root/daemon.json -peer-list-file /root/peers.txt -block-producer-key /keys/my-wallet -snark-worker-fee 0.002 -run-snark-worker B62qjVWFDi778HABEyQqujbznxdXTrWLbtLXBNnZJGfAY5cJ3VUjwMr -insecure-rest-server -file-log-level Debug -log-level Info -super-catchup
+ tail_pid=15
+ wait 14
+ tail -q -f coda.log
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
  ]
}
{"timestamp":"2021-01-27 04:26:57.965686Z","level":"Info","source":{"module":"Snark_worker__Functor","location":"File \"src/lib/snark_worker/functor.ml\", line 196, characters 10-21"},"message":"No jobs available. Napping for $time seconds","metadata":{"pid":124,"process":"Snark Worker","time":5.220560334419218}}
2021-01-27 04:27:01 UTC [Warn] RPC call error for "get_transition_chain_proof"
2021-01-27 04:27:03 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $error
	error: {
  "string":
    "RPC #145139 failed: \"internal RPC error error: unknown stream_idx\""
}
2021-01-27 04:27:03 UTC [Warn] failed to reset stream (this means it was probably closed successfully): $error
	error: {
  "string":
    "RPC #145140 failed: \"internal RPC error error: unknown stream_idx\""
}
2021-01-27 04:27:04 UTC [Warn] RPC call error for "get_transition_chain_proof"
2021-01-27 04:28:30 UTC [Info] Daemon child process 58 terminated after receiving signal "sigkill"
2021-01-27 04:28:30 UTC [Error] Child process of kind "Prover" with pid 58 has terminated
Coda process exited with status code 99
2021-01-27 04:28:42 UTC [Info] Coda daemon is booting up; built with commit "[DIRTY]a9402473584c36b347d52df4f4000b7286385987" on branch "HEAD"
Using password from environment variable CODA_PRIVKEY_PASS
2021-01-27 04:28:42 UTC [Info] Created daemon lockfile "/root/.coda-config/.mina-lock"
2021-01-27 04:28:42 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"
2021-01-27 04:28:42 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2021-01-27 04:28:42 UTC [Info] Booting may take several seconds, please wait
2021-01-27 04:28:42 UTC [Info] Reading configuration files $config_files
	config_files: [
  "/var/lib/coda/config_a9402473.json", "/root/.coda-config/daemon.json",
  "/root/daemon.json"
]
2021-01-27 04:28:42 UTC [Warn] Could not read configuration from "/root/.coda-config/daemon.json": $error
	error: {
  "exn_name": "Async_kernel__Monitor.Error_",
  "exn": [
    "monitor.ml.Error",
    [
      "Unix.Unix_error", "No such file or directory", "open",
      "((filename /root/.coda-config/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))"
    ],
+ echo 'Coda process exited with status code 99'
+ sleep 10
+ kill 15
+ '[' '!' -f stay_alive ']'
+ exit 0
+ mkdir -p .coda-config
+ touch .coda-config/coda-prover.log
+ touch .coda-config/coda-verifier.log
--
--
    "monitor.ml.Error",
    [ "Failure", "recursive add_exn failed" ],
    [
      "Raised at file \"stdlib.ml\", line 33, characters 17-33",
      "Called from file \"src/lib/network_pool/indexed_pool.ml\", line 928, characters 10-55",
      "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 947, characters 28-321",
      "Called from file \"src/result.ml\", line 96, characters 19-24",
      "Called from file \"src/deferred1.ml\", line 17, characters 40-45",
      "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5",
      "Called from file \"src/job_queue.ml\", line 171, characters 6-47",
      "Caught by monitor coda"
    ]
  ],
  "backtrace": [
    "Raised at file \"lib/read.mll\", line 712, characters 13-36",
    "Called from file \"lib/read.mll\", line 241, characters 23-47"
  ]
}
2021-01-27 05:58:06 UTC [Info] Daemon child process 75 terminated after receiving signal "sigkill"
2021-01-27 05:58:06 UTC [Error] Child process of kind "Prover" with pid 75 has terminated
Coda process exited with status code 99
+ touch .coda-config/mina-best-tip.log
+ command=daemon
+ shift
+ true
+ rm -f /root/.coda-config/.mina-lock
+ coda_pid=13
+ coda daemon -config-file /root/daemon.json -peer-list-file /root/peers.txt -block-producer-key /keys/my-wallet -snark-worker-fee 0.002 -run-snark-worker B62qjVWFDi778HABEyQqujbznxdXTrWLbtLXBNnZJGfAY5cJ3VUjwMr -insecure-rest-server -file-log-level Debug -log-level Info -super-catchup
+ tail_pid=14
+ tail -q -f coda.log
+ wait 13
2021-01-27 05:58:18 UTC [Info] Coda daemon is booting up; built with commit "[DIRTY]a9402473584c36b347d52df4f4000b7286385987" on branch "HEAD"
Using password from environment variable CODA_PRIVKEY_PASS
2021-01-27 05:58:18 UTC [Info] Created daemon lockfile "/root/.coda-config/.mina-lock"
2021-01-27 05:58:18 UTC [Info] Registering async shutdown handler: "Remove daemon lockfile"
2021-01-27 05:58:18 UTC [Info] Daemon will expire at "2024-12-10 14:00:00-07:00"
2021-01-27 05:58:18 UTC [Info] Booting may take several seconds, please wait
2021-01-27 05:58:18 UTC [Info] Reading configuration files $config_files
	config_files: [
  "/var/lib/coda/config_a9402473.json", "/root/.coda-config/daemon.json",
  "/root/daemon.json"

**Comment by mrmr1993** [comment]
From @gregbostrom in #7782:
> Version
> 
> ```
> mina-testnet-postake-medium-curves=0.2.12-718eba4
> Commit [DIRTY]718eba4826794f83d51c0d8dcf538e78b0259528 on branch HEAD
> ```
> 
> Last output:
> 
> ```
> 2021-02-03 07:31:04 UTC [Error] Daemon child process 18185 terminated after receiving signal "sigkill"
> 2021-02-03 07:31:04 UTC [Error] Possible reason for signal: "Process killed because out of memory"
> 2021-02-03 07:31:04 UTC [Error] Child process of kind "Prover" with pid 18185 has terminated
> ```
> 
> [coda.log](https://github.com/MinaProtocol/mina/files/5916943/coda.log)
> 
> [coda_crash_report_2021-02-03_07-29-24.491199.zip](https://github.com/MinaProtocol/mina/files/5916961/coda_crash_report_2021-02-03_07-29-24.491199.zip)

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
