### ISSUE TITLE
Show number of pending and applied commands in `client status`

### ISSUE THREAD

**Issue by fengwyeth** [MinaProtocol/mina#7649]
Why is my User_commands sent data different from that of my mina browser  data

**Comment by mrmr1993** [comment]
@MisterBigfeng can you update this issue with what you did, what you expected to see, and what you're actually seeing?

**Comment by MisterBigfeng** [comment]
I mean the number of transactions

**Comment by mrmr1993** [comment]
@MisterBigfeng what are you doing to get each of the disagreeing numbers?

**Comment by MisterBigfeng** [comment]
my linux User_commands sent numbers and browser Account Overview--Transactions--pending statistical data，i want to know if it's a delay or if the data is wrong

**Comment by mrmr1993** [comment]
Can you post the command you are running and its output? Please also attach the link to your pending transactions overview so that we can compare.

**Comment by MisterBigfeng** [comment]
one is 66  another  is 6

Global number of accounts:                     3707
Block height:                                  3151
Max observed block height:                     3151
Local uptime:                                  7h16m27s
Ledger Merkle root:                            jwo6WCuFJJeWPLGP6Vv3yuUcM4HLLweMrJaCAKwh1a2KioZcjYu
Protocol state hash:                           3NLZDfiy2vuBHC8NiVEAUowwNuu8JGzJ9bZDmt8bLNYRKBApTt3J
Chain id:                                      2dbac725ebb5c6c8b1daf21cda9e3694951ab72afe9be99ff7ca47574112f43b
Git SHA-1:                                     [DIRTY]5c08d6d51111d31269e77f3c62a544b3262ee4c8
Configuration directory:                       /home/lilymina/.coda-config
Peers:                                         2
User_commands sent:                            66
SNARK worker:                                  B62qnvF9EvCaushbDtgTr2C26RSHokvbriWYtTHCm2h5xu3q51RQLPY



Date | From | To | Hash | Fee | Amount
-- | -- | -- | -- | -- | --
  | Pending | B62qnvF9EvCaushbDtgTr2...Nonce: 194 | B62qjKK5CwGm2ce7MkFfuw... | Ckpa4hsHMuns59EDE9J9NA... | 22.000000000 | 0.001000000
  | Pending | B62qnvF9EvCaushbDtgTr2...Nonce: 195 | B62qjKK5CwGm2ce7MkFfuw... | CkpZZQpJxzp66i7zdRTh2u... | 22.000000000 | 0.001000000
  | Pending | B62qnvF9EvCaushbDtgTr2...Nonce: 196 | B62qjKK5CwGm2ce7MkFfuw... | CkpZT5GQgowVK4vRjmC86d... | 22.000000000 | 0.001000000
  | Pending | B62qnvF9EvCaushbDtgTr2...Nonce: 197 | B62qjKK5CwGm2ce7MkFfuw... | CkpZkZXURDixoDhvazsvGW... | 22.000000000 | 0.001000000
  | Pending | B62qnvF9EvCaushbDtgTr2...Nonce: 198 | B62qjKK5CwGm2ce7MkFfuw... | CkpaGvvrH1uVqdV1Xa6PN5... | 22.000000000 | 0.001000000
  | Pending | B62qnvF9EvCaushbDtgTr2...Nonce: 199 | B62qjKK5CwGm2ce7MkFfuw... | CkpZM3rTARt8hLXJPxDKhc... | 22.000000000 | 0.001000000
  | 2021-01-23 13:29:3028 minutes ago | B62qnvF9EvCaushbDtgTr2...Nonce: 193 | B62qoHkqbBmZFbGkpFjgbd... | CkpZwVaNoSEBvMTUHM8iq2... | 22.000000000 | 0.001000000

**Comment by mrmr1993** [comment]
I assume that the command you ran was `client status`, and that the 'browser' you're looking at is the [Mina Block Explorer](https://minaexplorer.com/wallet/B62qnvF9EvCaushbDtgTr2C26RSHokvbriWYtTHCm2h5xu3q51RQLPY).

`User_commands_sent` records the number of transactions sent to this current instance of your daemon. This gets reset after restarts. Your output indicates that you have sent 66 commands since you last started your daemon.

The block explorer shows that you have sent 199 commands since the beginning of this testnet, and all but 6 of them have been included in blocks.

As far as I can tell, there is nothing wrong here. However, I am going to leave this issue open and repurpose it for showing the `number of pending user commands` in the status, since this information would have been useful to see what is going on here.

**Comment by shimkiv** [comment]
Closing this issue as it is `stale` for a long time.
