### ISSUE TITLE
Integration Test: Peer Graph Connectivity

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#7683]
Extend the peers test to compute a peer graph representing how nodes are peering with one another. Create assertions that ensure the network topology is web-shaped and not wheel-shaped. Bonus: have a way to render this graph to a format for inspection (eg, use ocamlgraph to generate dot graphs).

Implementing this will fulfill the acceptance feature requirement for computing a peer graph.

**Comment by QuiteStochastic** [comment]
this test requires the seed node to be contacted via graphql, which is currently not working for some reason with the GCP based graphql ingress solution we have atm.  instead of debugging that, we're going to wait for https://github.com/MinaProtocol/mina/issues/8420 where we will use nginx for graphql ingress which should be a faster cleaner solution overall.  the only stipulation is that again, graphql for the seed node needs to work.  

other than that, I think this test is good.

**Comment by QuiteStochastic** [comment]
update, for whatever reason, the ingress controller for graphql requests is failing to contact the seed node, which prevents this integration test from working, because in this integration test we need to use graphql to talk to the seed node and not just the block producers.  other than that i think this test is fine, but this issue needs to be fixed before the test works.
