### ISSUE TITLE
Rosetta currently requires archive node running even though a subset of endpoints don't need it

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#7690]
Let's make it optional, and return errors in the requests that need it if it's not present

**Comment by omerzach** [comment]
It's pretty straightforward to do this based on top-level route—basically make `construction/*` not require Postgres at all but keep the others (`network/*`, `account/*`, `mempool/*, and `block/*`) depending on it. Making this more granular will require more boilerplate because we'll need to slide logic into each of the subrouters (`network.ml`, `account.ml`, `mempool.ml`, and `block.ml`) rather than just handling in `router.ml` where all the connection/pool logic lives now.

Happy to implement the granular side but I don't want to add that messiness unless we need/want that granularity.

**Comment by bkase** [comment]
this sounds great 👍 for an initial step

**Comment by omerzach** [comment]
It seems we need/want more granularity so I'm working on that; I think I found a good way to do it without adding much boilerplate.

https://github.com/MinaProtocol/mina/issues/8001
