### ISSUE TITLE
two servers running on same pub key showing different BP times

### ISSUE THREAD

**Issue by lampardlamps** [MinaProtocol/mina#7697]
<img width="1007" alt="Screenshot 2021-01-27 at 00 09 18" src="https://user-images.githubusercontent.com/1702296/105927385-daec5800-607e-11eb-8c1f-42320ed806ab.png">
<img width="1031" alt="Screenshot 2021-01-27 at 00 35 40" src="https://user-images.githubusercontent.com/1702296/105927400-dfb10c00-607e-11eb-96ca-51898cce432c.png">

**Comment by timsmith1337** [comment]
I have the same issue with same pub key yet two different time for BP. **_4.8hr is the actual time_** but this node (2nd picture) crashed due to network connectivity then I setup on **gcloud** (1st picture) which showed **none this epoch**. Later when I reinstalled my original node the right BP time came back. I did redo (deleted config) the gcloud yet BP time showing **none this epoch**.

![image](https://user-images.githubusercontent.com/77958700/106434207-6c066900-649b-11eb-862c-2c5fea593736.png)
![image](https://user-images.githubusercontent.com/77958700/106434228-76286780-649b-11eb-98df-35b6a9c63195.png)

**Comment by deepthiskumar** [comment]
@timsmith1337 could you link the logs for each of the nodes? You can run `coda client export-local-logs` command on each node to bundle all the log files in a tar file

**Comment by timsmith1337** [comment]
> coda client export-local-logs

Uploaded! https://c.mail.com/@651515830260999235/sJ-upQ1EQhy2zps9UhmTjw

After exporting the logs I stopped my node on gcloud, removed the .coda-config and restarted the daemon again. Now both nodes showing same BP time.

**Comment by deepthiskumar** [comment]
> > 
> Uploaded! https://c.mail.com/@651515830260999235/sJ-upQ1EQhy2zps9UhmTjw
> 
These don't have the vrf evaluation logs. @timsmith1337 if you see this next time, could you please export the logs immediately?

**Comment by bigant88** [comment]
After restarting, time to wait to produce block has increased from 4d to 11d. After the node synced, time back to 4d [](url)
<img width="907" alt="Screen Shot 2021-02-09 at 8 24 07 AM" src="https://user-images.githubusercontent.com/8001833/107303336-720ad400-6ab1-11eb-9dd3-7b79bd41a2f4.png">
<img width="890" alt="Screen Shot 2021-02-08 at 10 37 58 PM" src="https://user-images.githubusercontent.com/8001833/107303357-79ca7880-6ab1-11eb-84ef-19572c9c5851.png">
<img width="896" alt="Screen Shot 2021-02-08 at 10 38 17 PM" src="https://user-images.githubusercontent.com/8001833/107303360-7a630f00-6ab1-11eb-9300-0a02fb37fe88.png">

**Comment by emberian** [comment]
this was due to stale data being used for certain calculations, the output is more verbose thanks to #7859 and should prevent confusions in the future.
