### ISSUE TITLE
Make bestChain graphql endpoint asynchronous

### ISSUE THREAD

**Issue by bkase** [MinaProtocol/mina#7706]
It is very slow to process large bestChain queries. Since we perform this synchronously the node locks up during this time. It can’t, for example, process other queries.

It’s unclear why — it’s probably worth digging a bit, maybe it takes non-trivial time to convert a breadcrumb to json?
We should make this an io_field in graphql and do each breadcrumb in its own deferred block (assuming this is the bottleneck)

**Comment by psteckler** [comment]
I tried making using an `io_field1, and changing the `List.map` into a `Deferred.List.map ~how:`Parallel`, which didn't seem to help, because that just wraps the sequentially-computed blocks into a `Deferred.t`.

I let a local network reach a block height of 100, then timed getting a best chain via GraphQL. It actually took a bit longer with the `Deferred.List.map`.

**Comment by psteckler** [comment]
> Are we missing a yield? Wrapping each block in a separate deferred should at least free the client to handle other async tasks. 

I think `Parallel` does something like that:
```ocaml
   ...
  | `Parallel ->
    let rec loop i t (c : c Deferred.t) =
      match Sequence.next t with
      | None -> c
      | Some (a, t) ->
        loop
          (i + 1)
          t
          (let%bind b = mapi_f i a in
           let%map c = c in
           fold_f c b)
...
```
That appears to place the entire list of computations into the scheduler.

> Do we need an explicit scheduler yield?

Is that possible?

**Comment by bkase** [comment]
Yes we can improve the performance later. It’s just important in the short term that it doesn’t lockup the async task queue for all that time. And the yields can at least fix that part. Maybe we can make a new issue to improve performance too.

**Comment by mrmr1993** [comment]
If the issue is that we're taking up to much async time, we should use sequential.

Making the underlying chain construction async would also be nice -- although we would then have no guarantees that the chain wouldn't change out from under us during the call, so perhaps lets not do it now.

**Comment by psteckler** [comment]
Almost all the time is due to calling `Filtered_external_transition.of_transition`. Within that function, 30% - 90% of the time is from a call to `Transaction_hash.hash_command`.

With the existing code, and an async version using `Deferred.List.map`, running a local network, in both cases the time actually decreased as the blockchain increased in length.
