### ISSUE TITLE
Prometheus metric for prover errors

### ISSUE THREAD

**Issue by es92** [MinaProtocol/mina#7770]
This needs more discussion, and protocol to help with it

**Comment by deepthiskumar** [comment]
Since we are not running any block producers or snark workers, we'd have to add this to node-status(telemetry). The daemon could keep track of any blockchain snark errors and include that in the node-status output. 
For snark work failures, we currently crash when prover errors occur. We'll have to change that to return the error to the daemon, keep track of it and include it in the node-status output.
Are we ok taking these changes as hotfix? 

There is an alternative to observe transaction snark failures and that is to run snark workers with a new key and fee < account-creation-fee so that snarks are generated but don't get broadcasted. I can add snark-worker container crashes to the existing alerts
