### ISSUE TITLE
Slashing conditions in mainnet (grants programs)

### ISSUE THREAD

**Issue by c29r3** [MinaProtocol/mina#7982]
## Introduction  
For Mina Protocol grants, slashing is declared if the grant recipient does not comply with the terms of the agreement. The purpose of this issue is to clarify the specific conditions under which slashing is triggered  

## Questions  
1. What are the criteria for recalling a delegated stake?   
For example, a GFM member delegated his coins to someone from the staking providers list. Under what conditions can his stake will be revoked?   

2. What are the criteria for revoking a validator stake who delegated to himself?  
How many blocks should he miss in epoch? For example, for a stake of 66k MINA  

3. How does the grant revoked (technically)?  

## An example on the test network of Zenith  
There is a validator with 291 active delegations - https://minaexplorer.com/staking  
He has 30% of the total staked coins  - https://minaexplorer.com/wallet/B62qjCuPisQjLW7YkB22BR9KieSmUZTyApftqxsAuB3U21r3vj1YnaG    

![image](https://user-images.githubusercontent.com/52304443/108528609-a61d9a80-72e4-11eb-9eae-f21450a72e43.png)
![image](https://user-images.githubusercontent.com/52304443/108527483-60ac9d80-72e3-11eb-83dd-c08a1ef16bcb.png)  

```python
produced_blocks = 152
orphaned_blocks = 25
skiprate = orphaned_blocks / produced_blocks * 100
# 16.44% skiprate
```
Missed blocks may not depend on staking provider. Since multiple validators can produce a block in one slot.  If you take someone with fewer coins in the stake, there's a chance that he won't produce a single block in epoch  
![image](https://user-images.githubusercontent.com/52304443/108530140-54760f80-72e6-11eb-9037-dcd6fbcbae89.png)

**Comment by EmrePiconbello** [comment]
Change explained here which should explain all your questions but I am also giving simple short answers for some of them. https://github.com/MinaProtocol/mina/issues/7944#issuecomment-782104152
This answers your first 2 question 

"Missed blocks may not depend on staking provider. Since multiple validators can produce a block in one slot. If you take someone with fewer coins in the stake, there's a chance that he won't produce a single block in epoch" 

The above statement you make is also the reason for this change because the old system was taking average which can be lower for people even after 11 months because producers share the same slot. 

3) Through hard fork on genesis ledger.

**Comment by bkase** [comment]
Closing for #7944
