### ISSUE TITLE
LowPeerCount alert may need min_over_time to be valid (entering the query into a grafana query without it gives an error)

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8280]

**Comment by 0x0I** [comment]
The `LowPeerCount` alert expression seems to be behaving as expected and the current thinking is that the issue encountered was likely due to a URL encoding error. This problem should be resolved with updated testnet filter expressions and metric links as evidenced by the link below.

https://o1testnet.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-o1testnet-prom%22,%7B%22datasource%22:%22grafanacloud-o1testnet-prom%22,%22expr%22:%22min%20by(testnet)%20(Coda_Network_peers%7Btestnet!~%5C%22%5E(it-%7Cci-net).%2B%5C%22%7D)%20%3C%203%22,%22requestId%22:%22Q-5069994e-e17b-403e-8bac-a44195dd9a8e-0A%22%7D%5D

**Comment by deepthiskumar** [comment]
The metric has `min_over_time` currently and is working as expected  https://o1testnet.grafana.net/d/4BrFOXyMk/alerts?viewPanel=16&orgId=1&refresh=5s&var-testnet=mainnet
