### ISSUE TITLE
[TRIGGERED ALERT] mainet - NodesOutOfSync

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#8306]
Grafana metric: https://o1testnet.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-o1testnet-prom%22,%7B%22datasource%22:%22grafanacloud-o1testnet-prom%22,%22expr%22:%22Coda_watchdog_nodes_synced_near_best_tip%7Btestnet%3D%5C%22mainnet%5C%22%7D%22,%22requestId%22:%22Q-9455e2ec-aa1f-4d6f-af81-fe5abfe402bf-0A%22%7D%5D
Network health report: https://cdn.discordapp.com/attachments/774112816017571841/821699421141204992/block_tree.gv.png

Our seeds are all synced, but looking at the network health report, we can see that some nodes on the network are stuck on previous blocks. Only 4 / 157 of the nodes online are stuck at a chain with a common prefix > 3 blocks back.

### Updates

The updated network health report shows an improved state, though 3 nodes are still behind the best tip on the canonical chain. https://cdn.discordapp.com/attachments/774112816017571841/821706982003965972/block_tree.gv.png

----

A full hour after the alert began, network health reports now show only 1 node stuck on an older chain. Grafana metrics are now passing again.

### Recommended action

~~Reach out to community members that are stuck on old chains, ask them to restart their nodes to rejoin the chain. Also, attempt to collect any logs around this that we can so that we may debug and patch the issue.~~

After 1 hour, the nodes stuck on old chains caught up to the network's best tip. For the future, we may want to consider updating our alert so it wouldn't fire in these circumstances.

**Comment by deepthiskumar** [comment]
I think we need to add block height in the node status response to correctly determine NodesOutOfSync. Currently we get one of the latest blocks and check if all the other nodes have that as the best tip. We'd need the block height to compare and use state-hashes with max length among the responses. Until that change is introduced, this metric will be flaky because when there are multiple blocks per slot, some of them might not have heard of the newly accepted block yet and therefore counted as out-of-sync.  With the current implementation, it might also end up checking if all the nodes have an orphaned block as the best tip and I am suspecting this triggered the alert.
