### ISSUE TITLE
Snappnet - sendSnappCommand hangs and never makes it into a block and eventually causes crash

### ISSUE THREAD

**Issue by MartinMinkov** [MinaProtocol/mina#8317]
While running a daemon connected to snappnet and submitting a mutation made by the `credit-credit-check.exe prove` tool, the snapp command will never make it into a block and eventually cause a crash in the daemon. 

**Steps to reproduce:**
1) Connect to snappnet via the daemon
2) Issue the graphql output from the `credit-credit-check.exe prover` tool
3) Wait and monitor the network

When issuing the snapp command via GraphQL, the daemon will print its contents indicating that it's been seen. After some amount of time, the daemon will print out the following error:
```
2021-03-17 19:02:05 UTC [Info] Scheduled snapp transaction $command
...
...
2021-03-17 19:06:12 UTC [Warn] validation callback timed out before we could respond
2021-03-17 19:06:12 UTC [Error] validation timed out :(
```
Even though the snapp command was submitted, it will not be included in the next block and the network keeps moving along with making more blocks without including the snapp command. 

After submitting 3 different graphql mutations while running the daemon continously, the daemon will issue a `Fatal` error indicated below:
```
2021-03-17 19:20:06 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
...
```
[coda_crash_report_2021-03-17_19-20-06.188789.tar.gz](https://github.com/MinaProtocol/mina/files/6159187/coda_crash_report_2021-03-17_19-20-06.188789.tar.gz)

**Comment by mrmr1993** [comment]
Fixed in 4e8f26b (on branch `feature/snapp-demo-eth-addr`).

The fix is only needed for the node(s) sending snapp transactions: before rebroadcasting local transactions, they are sorted by nonce, which snapp commands don't necessarily have. All other nodes will not hit this codepath and will not encounter this issue.

In particular, the deployed nodes on snappnet do not need re-deploying with this fix.
