### ISSUE TITLE
Pull cryptographic libraries out of mina repo

### ISSUE THREAD

**Issue by imeckler** [MinaProtocol/mina#8621]
Currently, we have several crypto libraries that are tightly integrated with the rest of the mina application, but which should be generally useful. We should pull out the following libraries into their own opam packages (or perhaps some of them should be in the same package):

- src/lib/signature_lib
- src/lib/random_oracle
- src/lib/random_oracle_input
- src/lib/vrf_lib

This will let other people (and us) write tools to work with these primitives without having to pull in the whole mina repo.  For example, we had to duplicate all this code in https://github.com/MinaProtocol/signer-reference, where we could have just pulled in these libraries instead.

**Comment by mimoo** [comment]
some update: here's where I am currently, and what I'm trying to solve!

## Where to host?

It seems like the [o1-labs Github org](https://github.com/o1-labs/) is a good place to host these, and it seems like I have the rights to create a repo there, but it'd be good to have confirmation before I do :)

## Package vs packages

Do we want to make these submodules of a main `crypto` package? Or do we want to make them separate? From other discussions it seems like we wanted to make them separate (except perhaps for `random_oracle` and `random_oracle_input`).

## Dependencies

These packages rely on other stuff:

* internal mina packages like snark_params, ppx_coda, etc. should we move these too, or should we just add them to the [o1-labs opam repository](https://github.com/o1-labs/opam-repository/)?
* `config.mlh` constants used by preprocessors. This seems to be a all-in-one document of constants, do we want to only extract what's relevant instead of the whole thing?
* external packages not hosted on opam like ppx_version (which I'm suggesting we add to the [o1-labs opam repository here](https://github.com/o1-labs/opam-repository/pull/2)).

## Versioning and dependencies

I'm currently trying to understand why dependencies are listed redundantly in `dune` files, `package.opam` files, and `opam` files in the opam repository. We also don't seem to pin an exact version for each dependencies (is it an issue?)

(It looks like there's a tool called [opam-dune-lint](https://discuss.ocaml.org/t/ann-opam-dune-lint-keep-opam-and-dune-dependencies-in-sync/7014) that we can install in CI to make sure that dependencies in `dune` and `package.opam` files are matching.)

**Comment by mrmr1993** [comment]
> Do we want to make these submodules of a main `crypto` package? Or do we want to make them separate?

My preference is to keep them separate. 

> * internal mina packages like snark_params, ppx_coda, etc. should we move these too, or should we just add them to the [o1-labs opam repository](https://github.com/o1-labs/opam-repository/)?

`snark_params` is mostly a relic of snarky requiring its inputs being an entire proof system laid out in a particular way. I don't think there's anything of actual value there, it would be good if we could get to a stage where we can delete it. I don't think it's worth moving out to the opam repo.

`ppx_coda` should probably be split up:
* `check_ocaml_word_size` should be a program that runs at build-time, there's no need for it to be in the ppx
* `expires_after` should be a runtime check and not part of the ppx
* `ppx_enum` and `ppx_representatives` are already separate, they can be moved out
* `define_locally` and `getenv_ppx` should also be separated and then moved out

> * `config.mlh` constants used by preprocessors. This seems to be a all-in-one document of constants, do we want to only extract what's relevant instead of the whole thing?

`config.mlh` should only be referred to by mina-specific libraries, anything that's a standalone library shouldn't be referring to it at all. I've got a branch with some changes in this direction already, but there may be some extra work still to do here.

> I'm currently trying to understand why dependencies are listed redundantly in `dune` files, `package.opam` files, and `opam` files in the opam repository. We also don't seem to pin an exact version for each dependencies (is it an issue?)

I think we should try to move into a state where we can use dune-release, if it's not too much work.

**Comment by mimoo** [comment]
> snark_params is mostly a relic of snarky requiring its inputs being an entire proof system laid out in a particular way. I don't think there's anything of actual value there, it would be good if we could get to a stage where we can delete it. I don't think it's worth moving out to the opam repo.

I believe this is what I'm supposed to look at next (although not sure yet) https://github.com/o1-labs/snarky/issues/559

**Comment by psteckler** [comment]
`signature_lib` depends on `ppx_version`, is the thought to create an OPAM package for that?

**Comment by mimoo** [comment]
on our custom repo, see: https://github.com/o1-labs/opam-repository/pull/2

**Comment by mimoo** [comment]
update: I'm now focusing on `signature_lib` and reading code to understand how to extract things properly. I'm still running into the fact that it's tightly coupled with Mina and lots of these packages don't have comments. Packages also end up importing nonconsensus and consensus versions of different libraries depending on configuration. For example, `signature_lib` relies on hash_prefix_states which will import nonconsensus/consensus versions of Random_oracle and Mina_compile_config. I'm not too sure yet how to deal with this split.
