### ISSUE TITLE
Feature request: Prove number of slots a key has won in an epoch

### ISSUE THREAD

**Issue by garethtdavies** [MinaProtocol/mina#8677]
To evaluate the performance of staking pools if it were possible for a block producer to prove they won x slots in an epoch it would be possible to calculate a metric to determine the performance of a block producer based on actual blocks produced on the network. 

Currently, the best we can do is determine the expected slot winning % based on the proportion of stake, but this is subject to variance. Most lists of staking pools are based simply on sorting based on the total stake delegated and it is difficult to differentiate the better performing, often smaller, pools.

This is similar to the approach used to determine the initial Foundation delegations.

**Comment by mrmr1993** [comment]
This should be fairly easy. Concretely, to do are:
* GraphQL command to return all vrfs for an epoch
  - with batching, so that it doesn't stall the node
* GraphQL command to verify a vrf
* CLI command to compute vrfs (locally and over GraphQL)
* CLI command to verify vrfs
  - local only is probably fine, no reason to do a function call over GraphQL

**Comment by mrmr1993** [comment]
I had misremembered the details of the vrf implementation: the base group element `h` is derived from the hash and then `h^private_key` is calculated (instead of `(g^private_key)^hash = public_key^hash`). This means that we would need to expose the private key in order to check the vrfs.

It looks like we'll need to use a snark to hide the private key; I'll set up a circuit and do some profiling to see how plausible this is.

**Comment by mrmr1993** [comment]
It turned out that this was possible without a snark proof after all. I've opened PR #8814 to add advanced commands (and GraphQL queries) to expose/check the vrf evaluations; hopefully that provides the basis we need for supporting this.

**Comment by garethtdavies** [comment]
Closing as implemented 👍
