### ISSUE TITLE
Patch existing mainnet/devnet deployment to include syncStatus Label

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8744]

**Comment by deepthiskumar** [comment]
Current proposal: (yet to test if this will work)
1. Upgrade the helm chart version (to the one that has the sync status) and terraform apply deployments sequentially, after a pod is successfully created and the daemon is synced. Check if there are any dependencies that does not allow this (i.e., deployments in a single cluster running different helm chart versions).

2. Gather all the manual changes that were made to the deployments. This includes different images that each pod is running, different resource limits, cli flag, libp2p metric port etc
Currently some deployments have these changes and other don't. Make sure they all have them when redeploying

Alternate solution:
If the above solution doesn't work then we could deploy a different cluster of nodes `mainnet2` and destroy `mainnet` after all the nodes in `mainnet2` are synced and any required state is up-to-date.
This solution would require us to either update the seed list or have mainnet2 use the same libp2p keys (I'm not very sure how having two nodes run the same libp2p keypair will affect the network). We'll also need to ensure the persisted archive database is transferred to the new cluster as well.

In the long term we want to be able to specify in terraform to do rolling updates to our deployments. Our current implementation simply destroys all of them at once and creates new ones. We also want to be able to specify different configurations (helm charts or local variables) for different instances of the same resource type so that whatever manual updates we do now is tracked and lives in main.tf of the testnet.

**Comment by aneesharaines** [comment]
Checking to see if helm supports having different versions

**Comment by deepthiskumar** [comment]
1. Extracted deployments from mainnet and devnet and added to a new repo https://github.com/MinaProtocol/mina-deployments.
2. Updated 3 devnet nodes to include sync status labels.
    1. First `kubectl replace`, wait for the node to sync and then delete the old replica set. The nodes remain offline when there are multiple replica sets which cuases the health check to fail and therefore doesn't do rolling update.
   2. The old nodes seems to hang around for a bit after deletion and triggers Out-of-sync alert.

The images don't have the latest healthcheck changes that update these sync status labels and therefore we'll have to update the deployment again. Since alpha release is happening soon, I will update the remaining deployments post release to avoid creating a branch off master-qa+devnet

**Comment by deepthiskumar** [comment]
Blocked on not being able to deploy latest alerts. Current alert config does not have all the rules on compatible
