### ISSUE TITLE
Mina CI with OCaml 4.11.2

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8902]

**Comment by psteckler** [comment]
In #8898, all of CI passes, except for an expected failure of versioned-type change linting.

That failure occurs because types of the form `t sexp_opaque` become `t [@sexp.opaque]`. That is a literal change of type, hence the linter detects the change. But the type `t sexp_opaque` is type-equal to `t`, so there's no change in serialization.
