### ISSUE TITLE
Investigating the 30min when there were no blocks

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#8985]

**Comment by deepthiskumar** [comment]
There were no blocks between June 2 00:45 01:15 UTC i.e., 10 missed slots. Looking at the history, this has been the biggest gap between two blocks so far:
slots between two blocks | count
|------|-------
 |  10 |     1
|    9 |     2
|    8 |     3
|    7 |    18
|    6 |    41
|    5 |   161
|    4 |   485
|    3 |  1662
|    2 |  6144

From the logs of a few blockproducers who volunteered, i did not see any block production failure. In one of the logs I saw that there were two catchup failures around the same time when there were no blocks.
```2021-06-02T00:35:07Z {"timestamp":"2021-06-02 00:35:06.522021Z","level":"Fatal","source":{"module":"Init__Coda_run","location":"File \"src/app/cli/src/init/coda_run.ml\", line 603, characters 2-26"},"message":"Unhandled top-level exception: $exn\nGenerating crash report","metadata":{"exn":{"commit_id":"a42bdeef6b0c15ee34616e4df76c882b0c5c7c2a","sexp":["monitor.ml.Error",["Pipe_lib.Strict_pipe.Overflow(\"primary transitions\")"],["Raised at file \"src/lib/pipe_lib/strict_pipe.ml\", line 258, characters 34-79","Called from file \"src/pipe.ml\", line 873, characters 10-13","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47","Caught by monitor coda"]],"backtrace":["Raised at file \"src/lib/pipe_lib/strict_pipe.ml\", line 258, characters 34-79","Called from file \"src/pipe.ml\", line 873, characters 10-13","Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5","Called from file \"src/job_queue.ml\", line 171, characters 6-47"]},"host":"44.233.155.135","peer_id":"12D3KooWDnnZTV2Su5Sx7g6pDHYh8QNKbSzZhqsSLrfTMfLqWvMD","pid":13,"port":8812}}``` Another instance of this was reported here  #8738
This exception occurs when the primary transactions pipe for blocks from the network, which has a fixed capacity but is determined by network traffic at the time of starting up, fills up. It could be due to multiple blocks in a short period of time and some delay in processing those blocks that causes the pipe to overflow. It could be that multiple nodes crashed with around the same time- ones that had small capacity?
 if a node restarts and does not bootstrap(start from persisted state), the pipe capacity is smaller than that of the nodes that bootstrap from a clean slate. Explains why not all the nodes crash at the same time when there is a lot of block traffic.

**Comment by deepthiskumar** [comment]
Based on this graph between slots missed and transactions included in a block (both fee transfers and user commands), it is not clear to me if gossip traffic could have been a contributor to this. There are quite a few missed slots (>= 5 consecutive) even with lesser traffic. And in our seed logs or a few community logs, there were no rejected blocks either (which could indicate delay due to gossip latency?)
<img width="1294" alt="Screen Shot 2021-06-20 at 10 25 20 PM" src="https://user-images.githubusercontent.com/15304983/122711584-41813680-d217-11eb-9403-b02183076a74.png">

**Comment by mrmr1993** [comment]
We no longer have the logs for this. Closing.
