### ISSUE TITLE
Test 300K+ accounts fron genesis 

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9017]

**Comment by psteckler** [comment]
With `compatible`, specifying 300k accounts in the `daemon.json`, I'm able to start a daemon as a seed node.

Issue 1: if I try to export any of the ledgers, I get a segfault on the client side, which occurs during the JSON-formatting of the response.

Issue 2: I'm able to export the staged ledger by exporting under `gdb`, and placing those accounts in the `daemon.json`. That results in a stack overflow, apparently due to a call to `List.flatten`, which is not tail-recursive.

**Comment by psteckler** [comment]
Matthew reports that the segfault is really a stack overflow in C code. The fix might be to set a larger system stack before running.

**Comment by psteckler** [comment]
Confirmed, by Matthew and myself: increasing the stack size allows successful export of ledgers.

**Comment by psteckler** [comment]
I haven't been able to reproduce the stack overflow on daemon load. Presumably, that could be addressed by setting the system stack size to a suitable value.

On my desktop, it took about 17 minutes to start bootstrapping when loading a `daemon.json` with 300k accounts.

**Comment by psteckler** [comment]
Using a genesis ledger saved via `runtime_genesis_ledger`, the seed takes about 3 minutes to start bootstrapping.

**Comment by psteckler** [comment]
For any of the ledgers, it takes about a minute to export them. (The first run to export the staged ledger took about 1.5 minutes, but was faster on a subsequent try.)

Running `ulimit -s 16384` is sufficient to avoid a stack overflow.

**Comment by psteckler** [comment]
I was able to run a seed, two nodes, and a block producer with 300K accounts, and send a payment every second.

**Comment by psteckler** [comment]
Total memory usage on my machine was about 27Gb; when not running these tests, usage is about 4 Gb.

I didn't want to run these tests too long, the sensors on the motherboard were indicating overheating.
