### ISSUE TITLE
Create a script that creates bursts of txns on devnet 

### ISSUE THREAD

**Issue by aneesharaines** [MinaProtocol/mina#9027]

**Comment by deepthiskumar** [comment]
https://github.com/MinaProtocol/mina/pull/8983

**Comment by QuiteStochastic** [comment]
@aneesharaines at what regularity do we want these txn bursts (run the script once per day? week?)?  and how "intense" of a burst is it (100 txns? 1000?), in terms of number of transactions and the rate at which they are fired off (like 5 per second? or what)?

**Comment by QuiteStochastic** [comment]
@aneesharaines more questions:

1: how many different accounts needs to be associated with this burst of transactions?  can it be just two accounts sending a bunch of transactions to each other, or does it need to be multiple accounts sending transactions back and forth?  

2: should all of the transaction commands be directed at a single block producer node (this can be accomplished by this node holding all the keys involved in the transactions, or can be accomplished by having the node be sent signed commands so it doesn't need to hold any of the keys) ? if so should this block producer node be a node which i spin up upon the running of the script, or an existing node on devnet 2?  if not then I could find or spin up `n` number of nodes and spread the transactions across all of them nodes.

3: I will need access to at least one mina account (preferably just by having access to the priv key) on devnet2 which has oodles of money.  each time the script is run, money is expended in the "friction" of transactions because of transaction fees, and possibly also in account creation fees although the latter can be avoided if absolutely necessary, although why not because it's all fake money anyways.  as such i'd need a way to eventually "refill" the money in this account.  where can I find such an account and how do i ensure that it's always topped off with monopoly money?

**Comment by aneesharaines** [comment]
@QuiteStochastic - Yes this is for devnet2 (the standing pre-mainNet network that we have).  

- There should be txn every 2 seconds, although it would be great if you can make it configurable (so that we can tune the volume up or down as needed in the future) @deepthiskumar or @mrmr1993 - would this volume run into any rate limiting? 
- Can you use one of the existing nodes, in fact one of the existing whale accounts?    
- Can you make the script configurable such that it gets passed the set of accounts it should send the txns too? We can start with running it on two block producers (to send the txns back to each other) but make it so it should be easy to run more as needed (which would be more realistic)

**Comment by mrmr1993** [comment]
Bit late to this, but 1 every 2s is 90 every slot. Our bps can't produce every slot because they don't have enough stake as a proportion of the ledger, so that's 180 per block, bigger than our capacity. That's also faster than the rate limit, which I think works out at 0.66...

1 every 5s should be okay-ish,

**Comment by QuiteStochastic** [comment]
OK so i'm pretty much done, I'd just like to nail down the following parameters:

1: The txn burst tool will send transactions between two nodes, the first node needs to be one with lots of cash.  Which two nodes should we have?  Right now I'm using whale1 and fish1 on devnet2.

2: How often do we want the cronjob to run, once a week?  every day?

3: In accordance with matthew's comment, I'm setting the rate limit to 1 txn every 5s, we can tweak this later if we need.  (actually so far it seems like we never hit this limit, because a single graphql command seems to inherently take longer than 5s anyways.)  I still need to know how many total transactions to send, right now for development purposes I'm simply sending 11 txns.

**Comment by QuiteStochastic** [comment]
OK so i have it running 100 transactions on a cadence of every single day.  LMK if we want to tweak these parameters, until them i'm closing this ticket
