### ISSUE TITLE
distinguishing variable-length and fixed-length APIs for poseidon

### ISSUE THREAD

**Issue by mimoo** [MinaProtocol/mina#9032]
In order to differentiate uses of Poseidon that need padding (variable-length) or not (fixed-length) we should use two different APIs. The APIs should prevent misuse and allow OCaml to (statically?) enforce the size when using fixed-length. 

* **fixed-length**. `poseidon_fixed(domain_separation, input)` needs to enforce that all other usage of the same `domain_separation` use inputs of the same length.
* **variable-length**. `poseidon_variable(domain_separation, input)` needs to add a padding at the end of the input, before squeezing  (we can use the field element 1).

I'm not sure how we can enforce the property for the fixed-length one without linking the expected input length with the domain separation string. For example, it should be impossible for someone to call a combination of these:

* `poseidon_fixed(a, [1, 2])`
* `poseidon_fixed(a, [1, 2, 3])`
* `poseidon_variable(a, [1, 2])`

**Comment by mimoo** [comment]
What I think we should do: write the different hashes that we want to use as tuples: `(domain_seperation_string, input_length_expected)` where `input_length_expected = 0` would mean variable-length.

**Comment by jspada** [comment]
Sounds good to me!

For domain separation we could

1. Add the new hash prefix format `(domain_seperation_string, input_length_expected)`
2. Update code for generating initial sponge state from hash prefix strings to
	a. Support old format (e.g. `"MinaSignatureMainnet"`) for backward compatibility
	b. Generate unique initial sponge states for new format e.g. (`"MinaSignatureMainnet"`, `9`)

Next, could update the poseidon/sponge API so that when we instantiate poseidon
we specify whether it's fixed-length or variable-length.  For example, like this

```rust
@@ -16,6 +16,7 @@ pub trait SpongeConstants {
    const SPONGE_BOX: usize;
    const FULL_MDS: bool;
    const INITIAL_ARK: bool;
+   const FIXED_LENGTH: Option<u32>;
 }
```

`FIXED_LENGTH` | Behaviour
-|-
`None` | Current `mainnet` compatible
`0` | Pad with `1`
`> 0` | `fail` if input length != `FIXED_LENGTH` 

Ideally we'd like `fail` to be a static check, but probably not possible, so
we could just panic.

What do you think?

**Comment by jspada** [comment]
Adding link to more details https://hackmd.io/@mimoo/BkxHVa1iu

**Comment by mrmr1993** [comment]
This is an issue for o1js, not the protocol. Closing.
