### ISSUE TITLE
1.2.0 beta 1 dropping offline and stop responding.

### ISSUE THREAD

**Issue by EmrePiconbello** [MinaProtocol/mina#9165]
We catch a weird state for the node. Node gets dropped to offline state. After a while, we couldn't get any response from the node. We tried everything that came to our minds. Anyway, after a while node recovered back. Node was up for nearly 4 days.
https://drive.google.com/file/d/1Rl7Mehgzh9UiYqCVpV_jY4sUJA-CCO0E/view?usp=sharing

**Comment by EmrePiconbello** [comment]
Linking to #9157 while on our end it doesn't crash behaviour looks very similar.

**Comment by jrwashburn** [comment]
I've got a script [mina-status-monitor](https://github.com/jrwashburn/mina-node-install/blob/main/scripts/mina-status-monitor.sh) running and logging status every 5 minutes. Attached are logs since 7/1. Two things of note:

1) it is extremely frequent to have the node simply fail to return status (all the "/usr/local/bin/mina-status-monitor.sh: line 96: -: syntax error" are caused by not having a valid return from mina client status, which crashes the monitor script.)

2) this node first saw "Offline" then back to "Synced" on 7/3 and it occurred regularly until 7/4, then started again from 7/8 23:40 through 7/9 07:00. After a one-off on 7/9, fine until 7/10 11:10, then persistent again since. I should have logs for all of these periods (I'm exporting logs to gcs every 4 hours) so if it is useful to pull a specific timeframe, I should be able to do that. 

[mina-status-monitor.log](https://github.com/MinaProtocol/mina/files/6796135/mina-status-monitor.log)

**Comment by EmrePiconbello** [comment]
Issue 1 is very persistent through version keep happening for very long periods.
Issue 2 offline synced issue is also happening a lot while not sure what triggers it keeps happening till you restart the node logs from that is in #9172.
