### ISSUE TITLE
Profile snapp transactions

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#9228]
A snark worker as it is implemented needs to generate multiple proof for one transaction. Benchmark time taken to generate the proofs for various length of parties and authorization
similar to what's in `src/app/cli/src/init/transaction_snark_profiler.ml`

**Comment by psteckler** [comment]
I have a branch where the profiler takes an optional flag `--snapps`, which makes it generate a list of `Parties.t` instead of payments. In that case, the `--k` flag is required, because `Two_from_same` doesn't make sense, I think.

The profiler prints out some details, in case it's useful:
```
Snapp 0
  No. other parties = 3
  Predicates: Full,Nonce,Full
Snapp 1
  No. other parties = 9
  Predicates: Nonce,Full,Nonce,Nonce,Nonce,Nonce,Nonce,Full,Nonce
Snapp 2
  No. other parties = 7
  Predicates: Nonce,Nonce,Nonce,Nonce,Full,Nonce,Nonce
Snapp 3
  No. other parties = 9
  Predicates: Full,Nonce,Full,Nonce,Full,Nonce,Nonce,Nonce,Nonce
Snapp 4
  No. other parties = 11
  Predicates: Nonce,Full,Nonce,Full,Nonce,Nonce,Full,Full,Full,Nonce,Full
Snapp 5
  No. other parties = 11
  Predicates: Nonce,Full,Nonce,Nonce,Nonce,Full,Full,Full,Nonce,Nonce,Nonce
Snapp 6
  No. other parties = 7
  Predicates: Full,Full,Nonce,Nonce,Nonce,Full,Nonce
Snapp 7
  No. other parties = 5
  Predicates: Nonce,Full,Nonce,Nonce,Full
```

Issue: In the profiler, the call to `T.of_non_parties_transaction` fails. I think it needs to be replaced by 
`T.of_parties_segment_exn`, but I don't know how to provide the correct arguments for that function.

@mrmr1993 @A-Manning Do you know how that goes?
