### ISSUE TITLE
Generator for snapp transactions for unit tests

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#9244]

**Comment by mrmr1993** [comment]
For proofs and verification keys, we can use dummies (as long as we make sure only to use them in non-snark unit tests only, and not in integration tests).

It would be good to have a 'passing' generator and a 'failing' generator for a party, so that we can do quickcheck testing over both behaviours. For this purpose, it would be handy to accept a ledger and a protocol state for this purpose, so that the amounts and the account + protocol state predicates can be forced to match or fail as needed.

**Comment by psteckler** [comment]
> it would be handy to accept a ledger and a protocol state for this purpose

@mrmr1993 Sorry, not following. This is for the type `Party.t`?

Where would the ledger and protocol state be used?

**Comment by mrmr1993** [comment]
> Where would the ledger and protocol state be used?

@psteckler  They would be used when constructing the snapp predicate for the party. You need to know the ledger (or at least, the contents of the relevant account) to construct an interesting account predicate, and similarly you need a protocol state to construct a valid protocol state predicate.

**Comment by psteckler** [comment]
@mrmr1993 Still confused here.

A `Party.t` contains a `Predicate.t`, which is the type:
```ocaml
        | Full of Snapp_predicate.Account.Stable.V2.t
        | Nonce of Account.Nonce.Stable.V1.t
        | Accept
```
which doesn't contain a protocol state, that I can see. Given a public key and a ledger, I could make a predicate using either `Full` or `Nonce`. Does that sound right?

**Comment by mrmr1993** [comment]
A transaction is formed of a `Parties.t`, which also includes a protocol state predicate.
