### ISSUE TITLE
Move options from insecure into config/*

### ISSUE THREAD

**Issue by nholland94** [MinaProtocol/mina#963]

**Comment by cmr** [comment]
I opened https://github.com/CodaProtocol/coda/issues/1035. I think it's still good to have value-level copies for these, but could be convinced otherwise. I don't want to infect everything with `optcomp` when a simple `if` suffices - most uses don't need to be conditional compilation (but some do). Let's come back to this once that issue is done? The integration tests are a good example of something that _should_ be conditionally compiled out.

**Comment by cmr** [comment]
There's a few stragglers in `insecure.ml` still.
