### ISSUE TITLE
Validate all node roles for Kubernetes / Helm integration

### ISSUE THREAD

**Issue by joseandro** [MinaProtocol/mina#9817]
This issue is updated to document the validation and testing of Terraform / Helm for all node roles. 
Because both the Terraform and Helm configurations are new, validation is planned in 2 stages. 

**Stage 1:** Validate Terraform in isolation, using old node yaml files. 

- [x] Seed Node
- [x] Block Producer
- [x] Archive Node
- [x] Rosetta Node
- [x] Snark Worker Node
- [x] Snark Coordinator Node
- [x] Watchdog Node

**Comment by stevenplatt** [comment]
This item is completed. Terraform has been validated for deploying existing/old YAML configurations. 
This did surface a dependency of having a Kubernetes namespace matching "mainnet", but there were no other conflicts surfaced. 

Block propogation and other network activites were not tested with this deploy - partially due to limited Google Project resources. These items are being tested in a followup issue (https://github.com/MinaProtocol/mina/issues/10000).
