### ISSUE TITLE
Handle failed snapp transactions in the pool

### ISSUE THREAD

**Issue by deepthiskumar** [MinaProtocol/mina#9943]
Transactions that have valid proof/signature but fail when applied to the ledger remain in the pool until the next restart or until they are replaced. Senders of the transaction have no information about the status of their transaction until is included in a block. 

I'm proposing we add a cli  and graphQL command to apply a snapp transaction to the latest ledger state and return an error. (#9972)
Also, we could have block producers mark any failed transaction in the pool for it to be discarded when the pool is updated every block

**Comment by mrmr1993** [comment]
> Transactions that have valid proof/signature but fail when applied to the ledger remain in the pool until the next restart or until they are replaced.

This is straightforward to fix for block producers, but less so for all other nodes, since they aren't actively applying transactions. We probably need a fuzzer that tests that only transactions that apply to the ledger are entered into the pool, and similar to test that transactions are evicted from the pool when they are no longer applicable.

> I'm proposing we add a cli and graphQL command to apply a snapp transaction to the latest ledger state and return an error.

Big fan of this. Bonus points if it can (optionally) consume and emit a sparse ledger.

> Also, we could have block producers mark any failed transaction in the pool for it to be discarded when the pool is updated every block

Make sure we log these too: until we have the fuzzer, this is the best way we have of identifying such transactions.
